Bug fixing

diff --git a/git-flow-commit b/git-flow-commit
--- a/git-flow-commit
+++ b/git-flow-commit
@@ -36,64 +36,50 @@
 # policies, either expressed or implied, of Vincent Driessen.
 #
 
+init() {
+  require_git_repo
+  require_gitflow_initialized
+  gitflow_load_settings
+  BRANCH=$(git_do branch --no-color | grep '^\* ' | grep -v 'no branch' | sed 's/^* //g')
+}
+
 usage() {
-	echo "usage: git-flow clone <path to reference repository> <path to destination folder>"
-	echo "       see the git clone man page for further information"
+#	echo "usage: git-flow commit <commit_message>"
+	echo "usage: git-flow commit <arguments>"
+	echo "       see the git commit man page for further information"
 }
 
-require_source_arg() {
-	if [ "$SOURCE" = "" ]; then
-		warn "Missing argument <path to reference repository>"
-		usage
-		exit 1
-	fi
-}
-
-require_destination_arg() {
-	if [ "$DESTINATION" = "" ]; then
-		warn "Missing argument <path to destination folder>"
+require_message_arg() {
+	if [ "$MESSAGE" = "" ]; then
+		warn "Missing argument <commit_message>"
 		usage
 		exit 1
 	fi
 }
 
 cmd_default() {
-	parse_args "$@"
-	require_source_arg
-	require_destination_arg
-	# clone new repository using standard git clone command
-	git_do clone -b develop $SOURCE $DESTINATION || \
-	  die "Could not clone git repository '$SOURCE' into '$DESTINATION'."
-	# modify acccess permissions of cloned repository
-	if [ "$DESTINATION" = "." ]; then
-		DESTINATION=$PWD
-	fi
-	chmod -R o-rwx $DESTINATION
-	# initialize git-flow for cloned repository
-	cd "$DESTINATION/.git"
-	echo '[gitflow "branch"]' >> config
-	echo '	master = master' >> config
-	echo '	develop = develop' >> config
-	echo '[gitflow "prefix"]' >> config
-	echo '	feature = feature/' >> config
-	echo '	release = release/' >> config
-	echo '	hotfix = hotfix/' >> config
-	echo '	support = support/' >> config
-	echo '	versiontag = v' >> config
-	# create the local master branch following the remote master
-	gitflow_load_settings
-	git_do branch --track $MASTER_BRANCH $ORIGIN/$MASTER_BRANCH >/dev/null 2>&1 || \
-	  die "Could not create a local branch '$MASTER_BRANCH', based on the remote branch '$MASTER_BRANCH' from '$ORIGIN'."
+#	parse_args "$@"
+#	require_message_arg
+	if ! git_is_clean_working_tree; then
+		# record changes to the local and the remote repository
+#		git_do commit -a -m "$MESSAGE" >/dev/null 2>&1 || \
+		git_do commit "$@" >/dev/null 2>&1 || \
+		  die "Could not commit changes to local repository $BRANCH."
+		git_do fetch -q "$ORIGIN" "$BRANCH" >/dev/null 2>&1 || \
+		  die "Could not fetch $BRANCH from $ORIGIN."
+		git_do push origin "$BRANCH" >/dev/null 2>&1 || \
+		  die "Could not push to $BRANCH from $ORIGIN."
 
-	echo
-	echo "Summary of actions:"
-	echo "- A new git repository '$DESTINATION' was created, based on '$SOURCE'"
-	echo "- Access to the git repository '$DESTINATION' has been restricted for group 'others'"
-	echo "- Local branches '$MASTER_BRANCH' and '$DEVELOP_BRANCH' have been created following the corresponding branches from '$ORIGIN'"
-	echo "- Gitflow has been initialized for the cloned repository"
-	echo
-	echo "Now, you can start working. Have fun!"
-	echo
+		echo
+		echo "Summary of actions:"
+		echo "- Latest objects have been fetched from '$ORIGIN'"
+		echo "- Changes have been committed to the local and the remote branch '$BRANCH'"
+		echo  
+	else
+		echo
+		echo "There are no changes to be committed."
+		echo
+	fi
 }
 
 cmd_help() {
@@ -107,6 +93,5 @@ parse_args() {
 	eval set -- "${FLAGS_ARGV}"
 
 	# read arguments into global variables
-	SOURCE=$1
-	DESTINATION=$2
+	MESSAGE=$1
 }
diff --git a/git-flow-feature b/git-flow-feature
--- a/git-flow-feature
+++ b/git-flow-feature
@@ -48,6 +48,7 @@ usage() {
 	echo "usage: git-flow feature [list] [-v]"
 	echo "       git-flow feature start [-F] <name> [<base>]"
 	echo "       git-flow feature finish [-rFkDS] [<name|nameprefix>]"
+	echo "       git-flow feature delete [-l] <name>"
 	echo "       git-flow feature publish <name>"
 	echo "       git-flow feature track <name>"
 	echo "       git-flow feature diff [<name|nameprefix>]"
@@ -372,12 +373,15 @@ helper_finish_cleanup() {
 	require_branch "$BRANCH"
 	require_clean_working_tree
 
+	# push branches to origin
+	if flag fetch; then
+		git_do push "$ORIGIN" ":refs/heads/$BRANCH" >/dev/null 2>&1 || \
+		  die "Could not push to $BRANCH from $ORIGIN."
+		git_do push "$ORIGIN" "$DEVELOP_BRANCH" >/dev/null 2>&1 || \
+		  die "Could not push to $DEVELOP_BRANCH from $ORIGIN."
+	fi
+	
 	# delete branch
-#	if flag fetch; then
-		git_do push "$ORIGIN" ":refs/heads/$BRANCH" >/dev/null 2>&1
-#	fi
-	
-	
 	if noflag keep; then
 		git_do push origin ":$BRANCH" >/dev/null 2>&1
 		if flag force_delete; then
@@ -400,6 +404,35 @@ helper_finish_cleanup() {
 	echo
 }
 
+cmd_delete() {
+	DEFINE_boolean local false "only delete the local branch" l
+	parse_args "$@"
+
+	# sanity checks
+	require_branch "$BRANCH"
+
+	# change to branch develop
+	git_do checkout "$DEVELOP_BRANCH" >/dev/null 2>&1 || \
+	  die "Could not check out $DEVELOP_BRANCH."
+
+	# delete local branch
+	git_do branch -d "$BRANCH" >/dev/null 2>&1
+
+	if ! flag local; then
+		# delete remote branch
+		git_do push "$ORIGIN" ":refs/heads/$BRANCH" >/dev/null 2>&1
+	fi
+
+	echo
+	echo "Summary of actions:"
+	echo "- The local branch '$BRANCH' has been deleted"
+	if ! flag local; then
+		echo "- The remote branch '$ORIGIN/$BRANCH' has been deleted"
+	fi
+	echo "- You are now on branch '$DEVELOP_BRANCH'"
+	echo
+}
+
 cmd_publish() {
 	parse_args "$@"
 	expand_nameprefix_arg
@@ -407,17 +440,17 @@ cmd_publish() {
 	# sanity checks
 	require_clean_working_tree
 	require_branch "$BRANCH"
-	git_do fetch -q "$ORIGIN"
+	git_do fetch -q "$ORIGIN" >/dev/null 2>&1
 	require_branch_absent "$ORIGIN/$BRANCH"
 
 	# create remote branch
-	git_do push "$ORIGIN" "$BRANCH:refs/heads/$BRANCH"
-	git_do fetch -q "$ORIGIN"
+	git_do push "$ORIGIN" "$BRANCH:refs/heads/$BRANCH" >/dev/null 2>&1
+	git_do fetch -q "$ORIGIN" >/dev/null 2>&1
 
 	# configure remote tracking
-	git_do config "branch.$BRANCH.remote" "$ORIGIN"
-	git_do config "branch.$BRANCH.merge" "refs/heads/$BRANCH"
-	git_do checkout "$BRANCH"
+	git_do config "branch.$BRANCH.remote" "$ORIGIN" >/dev/null 2>&1
+	git_do config "branch.$BRANCH.merge" "refs/heads/$BRANCH" >/dev/null 2>&1
+	git_do checkout "$BRANCH" >/dev/null 2>&1
 
 	echo
 	echo "Summary of actions:"
@@ -435,11 +468,11 @@ cmd_track() {
 	# sanity checks
 	require_clean_working_tree
 	require_branch_absent "$BRANCH"
-	git_do fetch -q "$ORIGIN"
+	git_do fetch -q "$ORIGIN"  >/dev/null 2>&1
 	require_branch "$ORIGIN/$BRANCH"
 
 	# create tracking branch
-	git_do checkout -b "$BRANCH" "$ORIGIN/$BRANCH"
+	git_do checkout -b "$BRANCH" "$ORIGIN/$BRANCH" >/dev/null 2>&1
 
 	echo
 	echo "Summary of actions:"
diff --git a/git-flow-hotfix b/git-flow-hotfix
--- a/git-flow-hotfix
+++ b/git-flow-hotfix
@@ -49,6 +49,7 @@ usage() {
 	echo "usage: git-flow hotfix [list] [-v]"
 	echo "       git-flow hotfix start [-F] <version> [<base>]"
 	echo "       git-flow hotfix finish [-Fsumfpknod] <version>"
+	echo "       git-flow hotfix delete [-l] <version>"
 	echo "       git-flow hotfix publish <version>"
 	echo "       git-flow hotfix track <version>"
 }
@@ -283,17 +284,17 @@ cmd_publish() {
 	# sanity checks
 	require_clean_working_tree
 	require_branch "$BRANCH"
-	git_do fetch -q "$ORIGIN"
+	git_do fetch -q "$ORIGIN" >/dev/null 2>&1
 	require_branch_absent "$ORIGIN/$BRANCH"
 
 	# create remote branch
-	git_do push "$ORIGIN" "$BRANCH:refs/heads/$BRANCH"
-	git_do fetch -q "$ORIGIN"
+	git_do push "$ORIGIN" "$BRANCH:refs/heads/$BRANCH" >/dev/null 2>&1
+	git_do fetch -q "$ORIGIN" >/dev/null 2>&1
 
 	# configure remote tracking
-	git_do config "branch.$BRANCH.remote" "$ORIGIN"
-	git_do config "branch.$BRANCH.merge" "refs/heads/$BRANCH"
-	git_do checkout "$BRANCH"
+	git_do config "branch.$BRANCH.remote" "$ORIGIN" >/dev/null 2>&1
+	git_do config "branch.$BRANCH.merge" "refs/heads/$BRANCH" >/dev/null 2>&1
+	git_do checkout "$BRANCH" >/dev/null 2>&1
 
 	echo
 	echo "Summary of actions:"
@@ -311,11 +312,11 @@ cmd_track() {
 	# sanity checks
 	require_clean_working_tree
 	require_branch_absent "$BRANCH"
-	git_do fetch -q "$ORIGIN"
+	git_do fetch -q "$ORIGIN" >/dev/null 2>&1
 	require_branch "$ORIGIN/$BRANCH"
 
 	# create tracking branch
-	git_do checkout -b "$BRANCH" "$ORIGIN/$BRANCH"
+	git_do checkout -b "$BRANCH" "$ORIGIN/$BRANCH" >/dev/null 2>&1
 
 	echo
 	echo "Summary of actions:"
@@ -384,6 +385,7 @@ cmd_finish() {
 		if ! flag onlydevelop; then
 			local remote_tag="$ORIGIN/$(git config --get gitflow.prefix.release)"
 			if ! has_like $remote_tag $(git_remote_branches); then
+				echo
 				warn "A release branch does not exist. Merging only into the develop branch."
 				norelease=true
 #				release=false
@@ -407,6 +409,7 @@ cmd_finish() {
 					fi
 				done
 				if [ "$remote_branch" = "not_found" ]; then
+					echo
 					warn "A release branch does not exist. Merging only into the develop branch."
 					norelease=true
 #					release=false
@@ -557,5 +560,34 @@ cmd_finish() {
 	if noflag keep; then
 		echo "- You are now on branch '$DEVELOP_BRANCH'"
 	fi
+	echo
+}
+
+cmd_delete() {
+	DEFINE_boolean local false "only delete the local branch" l
+	parse_args "$@"
+
+	# sanity checks
+	require_branch "$BRANCH"
+
+	# change to branch develop
+	git_do checkout "$DEVELOP_BRANCH" >/dev/null 2>&1 || \
+	  die "Could not check out $DEVELOP_BRANCH."
+
+	# delete local branch
+	git_do branch -d "$BRANCH" >/dev/null 2>&1
+
+	if ! flag local; then
+		# delete remote branch
+		git_do push "$ORIGIN" ":refs/heads/$BRANCH" >/dev/null 2>&1
+	fi
+
+	echo
+	echo "Summary of actions:"
+	echo "- The local branch '$BRANCH' has been deleted"
+	if ! flag local; then
+		echo "- The remote branch '$ORIGIN/$BRANCH' has been deleted"
+	fi
+	echo "- You are now on branch '$DEVELOP_BRANCH'"
 	echo
 }
diff --git a/git-flow-release b/git-flow-release
--- a/git-flow-release
+++ b/git-flow-release
@@ -49,6 +49,7 @@ usage() {
 	echo "usage: git-flow release [list] [-v]"
 	echo "       git-flow release start [-F] <major/minor> [<base>]"
 	echo "       git-flow release finish [-FsumpkSo] <version>"
+	echo "       git-flow feature delete [-l] <name>"
 	echo "       git-flow release publish <name>"
 	echo "       git-flow release track <name>"
 }
@@ -197,6 +198,9 @@ require_major_minor_arg() {
 					((nextdot-=1))
 					local fronttag=${shorttag:0:nextdot}
 					if [ "$fronttag" -ge "$majortag" ]; then
+						if [ "$fronttag" -gt "$majortag" ]; then
+							minortag=0
+						fi
 						majortag=$fronttag
 						shorttag=${shorttag: ((nextdot+=1))}
 						nextdot=$(expr index "$shorttag" .)
@@ -430,17 +434,17 @@ cmd_publish() {
 	# sanity checks
 	require_clean_working_tree
 	require_branch "$BRANCH"
-	git_do fetch -q "$ORIGIN"
+	git_do fetch -q "$ORIGIN" >/dev/null 2>&1
 	require_branch_absent "$ORIGIN/$BRANCH"
 
 	# create remote branch
-	git_do push "$ORIGIN" "$BRANCH:refs/heads/$BRANCH"
-	git_do fetch -q "$ORIGIN"
+	git_do push "$ORIGIN" "$BRANCH:refs/heads/$BRANCH" >/dev/null 2>&1
+	git_do fetch -q "$ORIGIN" >/dev/null 2>&1
 
 	# configure remote tracking
-	git_do config "branch.$BRANCH.remote" "$ORIGIN"
-	git_do config "branch.$BRANCH.merge" "refs/heads/$BRANCH"
-	git_do checkout "$BRANCH"
+	git_do config "branch.$BRANCH.remote" "$ORIGIN" >/dev/null 2>&1
+	git_do config "branch.$BRANCH.merge" "refs/heads/$BRANCH" >/dev/null 2>&1
+	git_do checkout "$BRANCH" >/dev/null 2>&1
 
 	echo
 	echo "Summary of actions:"
@@ -458,15 +462,44 @@ cmd_track() {
 	# sanity checks
 	require_clean_working_tree
 	require_branch_absent "$BRANCH"
-	git_do fetch -q "$ORIGIN"
+	git_do fetch -q "$ORIGIN" >/dev/null 2>&1
 	require_branch "$ORIGIN/$BRANCH"
 
 	# create tracking branch
-	git_do checkout -b "$BRANCH" "$ORIGIN/$BRANCH"
+	git_do checkout -b "$BRANCH" "$ORIGIN/$BRANCH" >/dev/null 2>&1
 
 	echo
 	echo "Summary of actions:"
 	echo "- A new remote tracking branch '$BRANCH' was created"
 	echo "- You are now on branch '$BRANCH'"
+	echo
+}
+
+cmd_delete() {
+	DEFINE_boolean local false "only delete the local branch" l
+	parse_args "$@"
+
+	# sanity checks
+	require_branch "$BRANCH"
+
+	# change to branch develop
+	git_do checkout "$DEVELOP_BRANCH" >/dev/null 2>&1 || \
+	  die "Could not check out $DEVELOP_BRANCH."
+
+	# delete local branch
+	git_do branch -d "$BRANCH" >/dev/null 2>&1
+
+	if ! flag local; then
+		# delete remote branch
+		git_do push "$ORIGIN" ":refs/heads/$BRANCH" >/dev/null 2>&1
+	fi
+
+	echo
+	echo "Summary of actions:"
+	echo "- The local branch '$BRANCH' has been deleted"
+	if ! flag local; then
+		echo "- The remote branch '$ORIGIN/$BRANCH' has been deleted"
+	fi
+	echo "- You are now on branch '$DEVELOP_BRANCH'"
 	echo
 }
diff --git a/git-flow-support b/git-flow-support
--- a/git-flow-support
+++ b/git-flow-support
@@ -50,6 +50,7 @@ init() {
 usage() {
 	echo "usage: git-flow support [list] [-v]"
 	echo "       git-flow support start [-F] <name> <base>"
+	echo "       git-flow feature delete [-l] <name>"
 }
 
 cmd_default() {
@@ -212,5 +213,34 @@ cmd_start() {
 	echo "- You are now on branch '$BRANCH'"
 	echo
 	echo "Now, start committing on the support version."
+	echo
+}
+
+cmd_delete() {
+	DEFINE_boolean local false "only delete the local branch" l
+	parse_args "$@"
+
+	# sanity checks
+	require_branch "$BRANCH"
+
+	# change to branch develop
+	git_do checkout "$DEVELOP_BRANCH" >/dev/null 2>&1 || \
+	  die "Could not check out $DEVELOP_BRANCH."
+
+	# delete local branch
+	git_do branch -d "$BRANCH" >/dev/null 2>&1
+
+	if ! flag local; then
+		# delete remote branch
+		git_do push "$ORIGIN" ":refs/heads/$BRANCH" >/dev/null 2>&1
+	fi
+
+	echo
+	echo "Summary of actions:"
+	echo "- The local branch '$BRANCH' has been deleted"
+	if ! flag local; then
+		echo "- The remote branch '$ORIGIN/$BRANCH' has been deleted"
+	fi
+	echo "- You are now on branch '$DEVELOP_BRANCH'"
 	echo
 }
