Fetches for <branch> from <origin> are no longer stored in FETCH_HEAD, but in refs/remotes/<origin>/<branch>

diff --git a/git-flow-feature b/git-flow-feature
--- a/git-flow-feature
+++ b/git-flow-feature
@@ -302,8 +302,8 @@ cmd_start() {
 		echo "Executing Git command 'git checkout $BASE'"
 		git_do checkout "$BASE" >/dev/null 2>&1 || \
 		  die "Could not check out $BASE."
-		echo "Executing Git command 'git fetch -q $ORIGIN $BASE'"
-		git_do fetch -q "$ORIGIN" "$BASE" >/dev/null 2>&1 || \
+		echo "Executing Git command 'git fetch -q $ORIGIN $BASE:refs/remotes/$ORIGIN/$BASE'"
+		git_do fetch -q "$ORIGIN" "$BASE":refs/remotes/"$ORIGIN"/"$BASE" >/dev/null 2>&1 || \
 		  die "Could not fetch $BASE from $ORIGIN."
 		echo "Executing Git command 'git merge --no-commit $ORIGIN/$BASE'"
 		git_do merge --no-commit "$ORIGIN/$BASE" >/dev/null 2>&1  || {
@@ -359,8 +359,8 @@ cmd_finish() {
 	echo "Executing Git command 'git checkout $BRANCH'"
 	git_do checkout "$BRANCH" >/dev/null 2>&1 || \
 	  die "Could not check out $BRANCH."
-	echo "Executing Git command 'git fetch -q $ORIGIN $BRANCH'"
-	git_do fetch -q "$ORIGIN" "$BRANCH" >/dev/null 2>&1 || \
+	echo "Executing Git command 'git fetch -q $ORIGIN $BRANCH:refs/remotes/$ORIGIN/$BRANCH'"
+	git_do fetch -q "$ORIGIN" "$BRANCH":refs/remotes/"$ORIGIN"/"$BRANCH" >/dev/null 2>&1 || \
 	  die "Could not fetch $BRANCH from $ORIGIN."
 	echo "Executing Git command 'git remote prune origin'"
 	git_do remote prune origin >/dev/null 2>&1
@@ -421,18 +421,18 @@ cmd_finish() {
 	# branch $ORIGIN/$BRANCH should be existent, but check it anyway...
 	if has "$ORIGIN/$BRANCH" $(git_remote_branches); then
 		if flag fetch; then
-#			echo "Executing Git command 'git fetch -q $ORIGIN $BRANCH'"
-#			git_do fetch -q "$ORIGIN" "$BRANCH" >/dev/null 2>&1
+#			echo "Executing Git command 'git fetch -q $ORIGIN $BRANCH:refs/remotes/$ORIGIN/$BRANCH'"
+#			git_do fetch -q "$ORIGIN" "$BRANCH":refs/remotes/"$ORIGIN"/"$BRANCH" >/dev/null 2>&1
 			echo "Executing Git command 'git checkout $DEVELOP_BRANCH'"
 			git_do checkout "$DEVELOP_BRANCH" >/dev/null 2>&1 || \
 			  die "Could not check out $DEVELOP_BRANCH."
 			# Basically, the additional fetch is not necessary, but can be useful when the
 			# subsequent pull fails
-			echo "Executing Git command 'git fetch -q $ORIGIN $DEVELOP_BRANCH'"
-			git_do fetch -q "$ORIGIN" "$DEVELOP_BRANCH" >/dev/null 2>&1 || \
+			echo "Executing Git command 'git fetch -q $ORIGIN $DEVELOP_BRANCH:refs/remotes/$ORIGIN/$DEVELOP_BRANCH'"
+			git_do fetch -q "$ORIGIN" "$DEVELOP_BRANCH":refs/remotes/"$ORIGIN"/"$DEVELOP_BRANCH" >/dev/null 2>&1 || \
 			  die "Could not fetch $DEVELOP_BRANCH from $ORIGIN."
-			echo "Executing Git command 'git pull -q --no-commit $ORIGIN $DEVELOP_BRANCH'"
-			git_do pull -q --no-commit "$ORIGIN" "$DEVELOP_BRANCH" >/dev/null 2>&1 || {
+			echo "Executing Git command 'git pull -q --no-commit $ORIGIN $DEVELOP_BRANCH:refs/remotes/$ORIGIN/$DEVELOP_BRANCH'"
+			git_do pull -q --no-commit "$ORIGIN" "$DEVELOP_BRANCH":refs/remotes/"$ORIGIN"/"$DEVELOP_BRANCH" >/dev/null 2>&1 || {
 			  echo "*****************************************************************************************"
 			  die "WARNING: There were merge conflicts on $DEVELOP_BRANCH. Resolve them using git mergetool."
 			}
@@ -757,15 +757,15 @@ cmd_pull() {
 				exit 1
 			fi
 		else
-			echo "Executing Git command 'git pull -q $REMOTE $BRANCH'"
-			git_do pull -q "$REMOTE" "$BRANCH" || die "Failed to pull from remote '$REMOTE'."
+			echo "Executing Git command 'git pull -q $REMOTE $BRANCH:refs/remotes/$REMOTE/$BRANCH'"
+			git_do pull -q "$REMOTE" "$BRANCH":refs/remotes/"$REMOTE"/"$BRANCH" || die "Failed to pull from remote '$REMOTE'."
 		fi
 
 		echo "Pulled $REMOTE's changes into $BRANCH."
 	else
 		# set up the local branch clone for the first time
-		echo "Executing Git command 'git fetch -q $REMOTE $BRANCH'"
-		git_do fetch -q "$REMOTE" "$BRANCH" || die "Fetch failed."     # stores in FETCH_HEAD
+		echo "Executing Git command 'git fetch -q $REMOTE $BRANCH:refs/remotes/$REMOTE/$BRANCH'"
+		git_do fetch -q "$REMOTE" "$BRANCH":refs/remotes/"$REMOTE"/"$BRANCH" || die "Fetch failed."     # stores in FETCH_HEAD
 		echo "Executing Git command 'git branch --no-track $BRANCH FETCH_HEAD'"
 		git_do branch --no-track "$BRANCH" FETCH_HEAD || die "Branch failed."
 		echo "Executing Git command 'git checkout -q $BRANCH'"
@@ -791,8 +791,8 @@ cmd_update() {
 	  die "Could not check out $base."
 	echo "Executing Git command 'git remote prune origin'"
 	git_do remote prune origin >/dev/null 2>&1
-	echo "Executing Git command 'git fetch -q $ORIGIN $base'"
-	git_do fetch -q "$ORIGIN" "$base" >/dev/null 2>&1 || \
+	echo "Executing Git command 'git fetch -q $ORIGIN $base:refs/remotes/$ORIGIN/$base'"
+	git_do fetch -q "$ORIGIN" "$base":refs/remotes/"$ORIGIN"/"$base" >/dev/null 2>&1 || \
 	  die "Could not fetch $base from $ORIGIN."
 	echo "Executing Git command 'git merge --no-commit $ORIGIN/$base'"
 	git_do merge --no-commit "$ORIGIN/$base" >/dev/null 2>&1  || {
@@ -806,8 +806,8 @@ cmd_update() {
 	echo "Executing Git command 'git checkout $BRANCH'"
 	git_do checkout "$BRANCH" >/dev/null 2>&1 || \
 	  die "Could not check out $BRANCH."
-	echo "Executing Git command 'git fetch -q $ORIGIN $BRANCH'"
-	git_do fetch -q "$ORIGIN" "$BRANCH" >/dev/null 2>&1 || \
+	echo "Executing Git command 'git fetch -q $ORIGIN $BRANCH:refs/remotes/$ORIGIN/$BRANCH'"
+	git_do fetch -q "$ORIGIN" "$BRANCH":refs/remotes/"$ORIGIN"/"$BRANCH" >/dev/null 2>&1 || \
 	  die "Could not fetch $BRANCH from $ORIGIN."
 	echo "Executing Git command 'git merge --no-commit $ORIGIN/$BRANCH'"
 	git_do merge --no-commit "$ORIGIN/$BRANCH" >/dev/null 2>&1  || {
