Added possibility to start a support branch from a remote branch without having a local version of this branch

diff --git a/git-flow-support b/git-flow-support
--- a/git-flow-support
+++ b/git-flow-support
@@ -204,7 +204,9 @@ cmd_start() {
 
 	# create the local branch and the corresponding remote branch
 	if ! git_do checkout -b "$BRANCH" "$BASE" >/dev/null 2>&1; then
-		die "Could not create feature branch '$BRANCH'"
+		if ! git_do checkout -b "$BRANCH" "$ORIGIN/$BASE" >/dev/null 2>&1; then
+			die "Could not create support branch '$BRANCH'"
+		fi
 	else
 		git_do push origin "$BRANCH" >/dev/null 2>&1
 	fi
