Modified git-flow release command to meet the requirements demanded by the new pasimodo branching model

diff --git a/git-flow-hotfix b/git-flow-hotfix
--- a/git-flow-hotfix
+++ b/git-flow-hotfix
@@ -48,7 +48,7 @@ init() {
 usage() {
 	echo "usage: git-flow hotfix [list] [-v]"
 	echo "       git-flow hotfix start [-F] <version> [<base>]"
-	echo "       git-flow hotfix finish [-Fsumpkr] <version>"
+	echo "       git-flow hotfix finish [-Fsumfpknod] <version>"
 	echo "       git-flow hotfix publish <version>"
 	echo "       git-flow hotfix track <version>"
 }
@@ -121,7 +121,7 @@ cmd_list() {
 					printf "(based on $nicename)"
 				fi
 			else
-				printf "%s" "$branch"
+				printf "%s" "$PREFIX$branch"
 			fi
 			echo
 		done
@@ -162,7 +162,7 @@ parse_args() {
 		local len=${#VERSION}-1
 		VERSION=${VERSION:0:len}
 	fi
-	# is there is no hotfix tag provided by the user, get the latest one from the server
+	# if there is no hotfix tag provided by the user, get the latest one from the server
 	number_dots="${VERSION//[^.]}"
 	if [ "${#number_dots}" = 1 ]; then
 		local last=0
@@ -174,11 +174,13 @@ parse_args() {
 				shorttag=${tag:len}
 				local nextdot
 				nextdot=$(expr index "$shorttag" .)
-				if [[ "$nextdot" > 0 ]]; then
+				if [[ "$nextdot" -gt 0 ]]; then
 					((nextdot-=1))
 					shorttag=${shorttag:0:nextdot}
 				fi
-				last=$shorttag
+				if [[ "$shorttag" -gt "$last" ]]; then
+					last=$shorttag
+				fi
 			fi
 		done
 		local newlast
@@ -199,7 +201,7 @@ parse_args() {
 		((newlast=last+1))
 		NEW_BRANCH=$PREFIX$VERSION_PREFIX$prefix.$newlast
 		NEW_VERSION=$prefix.$newlast
-	elif [[ "${#number_dots}" > 2 ]]; then
+	elif [[ "${#number_dots}" -gt 2 ]]; then
 		die "Subhotfix branches are not supported."
 	fi
 	BRANCH=$PREFIX$VERSION_PREFIX$VERSION
@@ -214,7 +216,7 @@ require_version_arg() {
 }
 
 require_base_is_on_master() {
-	if ! git branch --no-color --contains "$BASE" 2>/dev/null \
+	if ! git_do branch --no-color --contains "$BASE" 2>/dev/null \
 			| sed 's/[* ] //g' \
 	  		| grep -q "^$MASTER_BRANCH\$"; then
 		die "fatal: Given base '$BASE' is not a valid commit on '$MASTER_BRANCH'."
@@ -233,7 +235,6 @@ cmd_start() {
 	DEFINE_boolean fetch false "fetch from $ORIGIN before performing finish" F
 	parse_args "$@"
 	BASE=${2:-$MASTER_BRANCH}
-
 	require_version_arg
 #	require_base_is_on_master
 	require_no_existing_hotfix_branches
@@ -246,6 +247,8 @@ cmd_start() {
 	if flag fetch; then
 		git_do fetch -q "$ORIGIN" "$MASTER_BRANCH" >/dev/null 2>&1
 	fi
+	# if the origin branch counterpart exists, assert that the local branch
+	# isn't behind it (to avoid unnecessary rebasing)
 	if has "$ORIGIN/$MASTER_BRANCH" $(git_remote_branches); then
 		require_branches_equal "$MASTER_BRANCH" "$ORIGIN/$MASTER_BRANCH"
 	fi
@@ -269,7 +272,7 @@ cmd_start() {
 #	echo "- When done, run:"
 	echo "Now, start committing your hotfixes. When done, use:"
 	echo
-	echo "     git-flow hotfix finish '$VERSION_PREFIX$NEW_VERSION'"
+	echo "     git-flow hotfix finish $VERSION_PREFIX$NEW_VERSION"
 	echo
 }
 
@@ -288,8 +291,8 @@ cmd_publish() {
 	git_do fetch -q "$ORIGIN"
 
 	# configure remote tracking
-	git config "branch.$BRANCH.remote" "$ORIGIN"
-	git config "branch.$BRANCH.merge" "refs/heads/$BRANCH"
+	git_do config "branch.$BRANCH.remote" "$ORIGIN"
+	git_do config "branch.$BRANCH.merge" "refs/heads/$BRANCH"
 	git_do checkout "$BRANCH"
 
 	echo
@@ -330,7 +333,8 @@ cmd_finish() {
 	DEFINE_boolean push true "push to $ORIGIN after performing finish" p
 	DEFINE_boolean keep false "keep branch after performing finish" k
 	DEFINE_boolean notag false "don't tag this release" n
-	DEFINE_boolean release false "merge the current hotfix branch into the release branch instead of the develop branch" r
+	DEFINE_boolean onlymaster false "merge the current hotfix branch only into the master branch" o
+	DEFINE_boolean onlydevelop false "merge the current hotfix branch only into the develop branch and not into an existing release branch (requires flag -o is absent)" d
 	parse_args "$@"
 	require_version_arg
 
@@ -358,20 +362,9 @@ cmd_finish() {
 		require_branches_equal "$BRANCH" "$ORIGIN/$BRANCH"
 	fi
 
-	# try to merge into master
-	# in case a previous attempt to finish this release branch has failed,
-	# but the merge into master was successful, we skip it now
-	if ! git_is_branch_merged_into "$BRANCH" "$MASTER_BRANCH"; then
-		git_do checkout "$MASTER_BRANCH" || \
-		  die "Could not check out $MASTER_BRANCH."
-		git_do merge --no-ff "$BRANCH" || \
-		  die "There were merge conflicts."
-		  # TODO: What do we do now?
-	fi
-
 	if noflag notag; then
-		# try to tag the release
-		# in case a previous attempt to finish this release branch has failed,
+		# try to tag the hotfix
+		# in case a previous attempt to finish this hotfix branch has failed,
 		# but the tag was set successful, we skip it now
 		local tagname=$VERSION_PREFIX$VERSION
 		if ! git_tag_exists "$tagname"; then
@@ -380,103 +373,137 @@ cmd_finish() {
 			[ "$FLAGS_signingkey" != "" ] && opts="$opts -u '$FLAGS_signingkey'"
 			[ "$FLAGS_message" != "" ] && opts="$opts -m '$FLAGS_message'"
 			[ "$FLAGS_messagefile" != "" ] && opts="$opts -F '$FLAGS_messagefile'"
-			eval git_do tag $opts "$VERSION_PREFIX$VERSION" "$BRANCH" || \
+			eval git_do tag $opts "$tagname" "$BRANCH" || \
 			die "Tagging failed. Please run finish again to retry."
 		fi
 	fi
 
-	if flag release; then
-		local remote_tag="$ORIGIN/$(git config --get gitflow.prefix.release)"
-		if ! has_like $remote_tag $(git_remote_branches); then
-			warn "A release branch does not exist. Merging into develop branch instead."
-			release=false
-		else
-			local remote_branches
-			remote_branches="$(git_remote_branches)"
-			local remote_branch="not_found"
-			local find_branch
-			for find_branch in $remote_branches; do
-				if { echo "$find_branch" | grep -q "^$remote_tag"; } then
-				remote_branch="$find_branch"
-				fi
-			done
-			local local_branches
-			local_branches="$(git_local_branches)"
-			local local_branch="not_found"
-			local local_tag="$(git config --get gitflow.prefix.release)"
-			for find_branch in $local_branches; do
-				if { echo "$find_branch" | grep -q "^$local_tag"; } then
-				local_branch="$find_branch"
-				fi
-			done
-			if [ "$remote_branch" = "not_found" ]; then
-				warn "A release branch does not exist. Merging into develop branch instead."
-				release=false
+	local norelease=false
+	if ! flag onlymaster; then
+#		if flag release; then
+		if ! flag onlydevelop; then
+			local remote_tag="$ORIGIN/$(git config --get gitflow.prefix.release)"
+			if ! has_like $remote_tag $(git_remote_branches); then
+				warn "A release branch does not exist. Merging only into the develop branch."
+				norelease=true
+#				release=false
 			else
-				if ! git_is_branch_merged_into "$BRANCH" "$remote_branch"; then
-					# try to merge into remote release branch
-					# in case a previous attempt to finish this hotfix branch has failed,
-					# but the merge into the remote release branch was successful, we skip it now
-#					local remote_shortname
-#					local len=${#remote_tag}
-#					remote_shortname=${remote_branch:len}
-					local len=${#ORIGIN}
-					((len+=1))
-					local local_name=${remote_branch:len}
-					if [ "$local_branch" = "not_found" ]; then
-						git_do branch --track $local_name $remote_branch >/dev/null 2>&1
-						git_do checkout "$local_name" >/dev/null 2>&1 || \
-						  die "Could not check out $local_name."
-						git_do merge --no-ff "$BRANCH" >/dev/null 2>&1 || \
-						  die "There were merge conflicts."
-						  # TODO: What do we do now?
-						git_do push "$ORIGIN" "$local_name" >/dev/null 2>&1 || \
-						  die "Could not push to $local_name from $ORIGIN."
-						git_do checkout "$BRANCH" >/dev/null 2>&1 || \
-						  die "Could not check out $BRANCH."
-						git_do branch -d "$local_name" >/dev/null 2>&1
-					else
-						git_do checkout "$local_name" >/dev/null 2>&1 || \
-						  die "Could not check out $local_name."
-#						if flag fetch; then
-							git_do fetch "$ORIGIN" "$local_name" >/dev/null 2>&1 || \
-							  die "Could not fetch $local_name from $ORIGIN."
-#						fi
-						git_do merge --no-ff "$BRANCH" >/dev/null 2>&1 || \
-						  die "There were merge conflicts."
-						  # TODO: What do we do now?
-						git_do push "$ORIGIN" "$local_name" >/dev/null 2>&1 || \
-						  die "Could not push to $local_name from $ORIGIN."
-						git_do checkout "$BRANCH" >/dev/null 2>&1 || \
-						  die "Could not check out $BRANCH."
-						
+				local remote_branches
+				remote_branches="$(git_remote_branches)"
+				local remote_branch="not_found"
+				local find_branch
+				for find_branch in $remote_branches; do
+					if { echo "$find_branch" | grep -q "^$remote_tag"; } then
+					remote_branch="$find_branch"
+					fi
+				done
+				local local_branches
+				local_branches="$(git_local_branches)"
+				local local_branch="not_found"
+				local local_tag="$(git config --get gitflow.prefix.release)"
+				for find_branch in $local_branches; do
+					if { echo "$find_branch" | grep -q "^$local_tag"; } then
+					local_branch="$find_branch"
+					fi
+				done
+				if [ "$remote_branch" = "not_found" ]; then
+					warn "A release branch does not exist. Merging only into the develop branch."
+					norelease=true
+#					release=false
+				else
+					if ! git_is_branch_merged_into "$BRANCH" "$remote_branch"; then
+						# try to merge into remote release branch
+						# in case a previous attempt to finish this hotfix branch has failed,
+						# but the merge into the remote release branch was successful, we skip it now
+#						local remote_shortname
+#						local len=${#remote_tag}
+#						remote_shortname=${remote_branch:len}
+						local len=${#ORIGIN}
+						((len+=1))
+						local local_name=${remote_branch:len}
+						if [ "$local_branch" = "not_found" ]; then
+							git_do branch --track $local_name $remote_branch >/dev/null 2>&1
+							git_do checkout "$local_name" >/dev/null 2>&1 || \
+							  die "Could not check out $local_name."
+							git_do merge --no-ff "$BRANCH" >/dev/null 2>&1 || \
+							  die "There were merge conflicts."
+							  # TODO: What do we do now?
+							git_do push "$ORIGIN" "$local_name" >/dev/null 2>&1 || \
+							  die "Could not push to $local_name from $ORIGIN."
+							git_do checkout "$BRANCH" >/dev/null 2>&1 || \
+							  die "Could not check out $BRANCH."
+							git_do branch -d "$local_name" >/dev/null 2>&1
+						else
+							git_do checkout "$local_name" >/dev/null 2>&1 || \
+							  die "Could not check out $local_name."
+#							if flag fetch; then
+								git_do fetch "$ORIGIN" "$local_name" >/dev/null 2>&1 || \
+								  die "Could not fetch $local_name from $ORIGIN."
+#							fi
+							git_do merge --no-ff "$BRANCH" >/dev/null 2>&1 || \
+							  die "There were merge conflicts."
+							  # TODO: What do we do now?
+							git_do push "$ORIGIN" "$local_name" >/dev/null 2>&1 || \
+							  die "Could not push to $local_name from $ORIGIN."
+							git_do checkout "$BRANCH" >/dev/null 2>&1 || \
+							  die "Could not check out $BRANCH."
+							
+						fi
 					fi
 				fi
 			fi
 		fi
+
+#		if ! flag release; then
+			# try to merge into develop
+			# in case a previous attempt to finish this hotfix branch has failed,
+			# but the merge into develop was successful, we skip it now
+			git_do fetch -q "$ORIGIN" "$DEVELOP_BRANCH" >/dev/null 2>&1 || \
+			  die "Could not fetch $DEVELOP_BRANCH from $ORIGIN."
+			if ! git_is_branch_merged_into "$BRANCH" "$ORIGIN/$DEVELOP_BRANCH"; then
+				git_do checkout "$DEVELOP_BRANCH" >/dev/null 2>&1 || \
+				  die "Could not check out $DEVELOP_BRANCH."
+
+				# TODO: Actually, accounting for 'git describe' pays, so we should
+				# ideally git merge --no-ff $tagname here, instead!
+				git_do merge --no-ff "$BRANCH" >/dev/null 2>&1 || \
+				  die "There were merge conflicts."
+				  # TODO: What do we do now?
+
+				git_do push "$ORIGIN" "$DEVELOP_BRANCH" >/dev/null 2>&1 || \
+				  die "Could not push to $DEVELOP_BRANCH from $ORIGIN."
+				git_do checkout "$BRANCH" >/dev/null 2>&1 || \
+				  die "Could not check out $BRANCH."
+			fi
+#		fi
 	fi
 
-	if ! flag release; then
-		# try to merge into develop
-		# in case a previous attempt to finish this hotfix branch has failed,
-		# but the merge into develop was successful, we skip it now
-		git_do fetch -q "$ORIGIN" "$DEVELOP_BRANCH" >/dev/null 2>&1 || \
-		  die "Could not fetch $DEVELOP_BRANCH from $ORIGIN."
-		if ! git_is_branch_merged_into "$BRANCH" "$ORIGIN/$DEVELOP_BRANCH"; then
-			git_do checkout "$DEVELOP_BRANCH" >/dev/null 2>&1 || \
-			  die "Could not check out $DEVELOP_BRANCH."
-
-			# TODO: Actually, accounting for 'git describe' pays, so we should
-			# ideally git merge --no-ff $tagname here, instead!
-			git_do merge --no-ff "$BRANCH" >/dev/null 2>&1 || \
-			  die "There were merge conflicts."
-			  # TODO: What do we do now?
-
-			git_do push "$ORIGIN" "$DEVELOP_BRANCH" >/dev/null 2>&1 || \
-			  die "Could not push to $DEVELOP_BRANCH from $ORIGIN."
-			git_do checkout "$BRANCH" >/dev/null 2>&1 || \
-			  die "Could not check out $BRANCH."
-		fi
+	# try to merge into master
+	# in case a previous attempt to finish this hotfix branch has failed,
+	# but the merge into master was successful, we skip it now
+	if ! git_is_branch_merged_into "$BRANCH" "$MASTER_BRANCH"; then
+#		# first, find the tag of the previous version
+#		local previoustag
+#		previoustag=git_do describe --abbrev=0 --tags
+#		git_do checkout "$MASTER_BRANCH" >/dev/null 2>&1 || \
+#		  die "Could not check out $MASTER_BRANCH."
+#		git_do checkout "$previoustag" >/dev/null 2>&1 || \
+#		  die "Could not check out $previoustag."
+#		git_do commit --amend -v >/dev/null 2>&1 || \
+#		  die "There were merge conflicts."
+#		  # TODO: What do we do now?
+		git_do merge --no-ff "$MASTER_BRANCH" >/dev/null 2>&1 || \
+		  die "There were merge conflicts."
+		  # TODO: What do we do now?
+		git_do push "$BRANCH":"$ORIGIN/$MASTER_BRANCH" >/dev/null 2>&1 || \
+		  die "Could not push to $ORIGIN/$MASTER_BRANCH from $BRANCH."
+		git_do checkout "$MASTER_BRANCH" >/dev/null 2>&1 || \
+		  die "Could not check out $MASTER_BRANCH."
+		git_do fetch -q "$ORIGIN" "$MASTER_BRANCH" >/dev/null 2>&1 || \
+		  die "Could not fetch $MASTER_BRANCH from $ORIGIN."
+		require_branches_equal "$MASTER_BRANCH" "$ORIGIN/$MASTER_BRANCH"
+		git_do checkout "$BRANCH" >/dev/null 2>&1 || \
+		  die "Could not check out $BRANCH."
 	fi
 
 	if flag push; then
@@ -503,8 +530,11 @@ cmd_finish() {
 #	if noflag notag; then
 		echo "- The hotfix was tagged '$VERSION_PREFIX$VERSION'"
 #	fi
-	if flag release; then
-		echo "- Hotfix branch has been back-merged into the existing release branch"
+#	if flag release; then
+	if ! flag onlymaster; then
+		if [ "$onlydevelop" != "true" ] && [ "$norelease" != "true" ]; then
+			echo "- Hotfix branch has been back-merged into the existing release branch"
+		fi
 	else
 		echo "- Hotfix branch has been back-merged into '$DEVELOP_BRANCH'"
 	fi
@@ -514,7 +544,15 @@ cmd_finish() {
 		echo "- Hotfix branch '$BRANCH' (local and remote) has been deleted"
 	fi
 	if flag push; then
-		echo "- '$DEVELOP_BRANCH', '$MASTER_BRANCH' and tags have been pushed to '$ORIGIN'"
+		if ! flag onlymaster; then
+			echo "- '$MASTER_BRANCH' and tags have been pushed to '$ORIGIN'"
+		else
+			if [ "$norelease" != "true" ]; then
+				echo "- '$DEVELOP_BRANCH', the release branch, '$MASTER_BRANCH' and tags have been pushed to '$ORIGIN'"
+			else
+				echo "- '$DEVELOP_BRANCH', '$MASTER_BRANCH' and tags have been pushed to '$ORIGIN'"
+			fi
+		fi
 	fi
 	if noflag keep; then
 		echo "- You are now on branch '$DEVELOP_BRANCH'"
diff --git a/git-flow-release b/git-flow-release
--- a/git-flow-release
+++ b/git-flow-release
@@ -42,12 +42,13 @@ init() {
   gitflow_load_settings
   VERSION_PREFIX=$(eval "echo `git config --get gitflow.prefix.versiontag`")
   PREFIX=$(git config --get gitflow.prefix.release)
+  REMOTE_PREFIX=$ORIGIN/$PREFIX
 }
 
 usage() {
 	echo "usage: git-flow release [list] [-v]"
-	echo "       git-flow release start [-F] <version> [<base>]"
-	echo "       git-flow release finish [-FsumpkS] <version>"
+	echo "       git-flow release start [-F] <major/minor> [<base>]"
+	echo "       git-flow release finish [-FsumpkSo] <version>"
 	echo "       git-flow release publish <name>"
 	echo "       git-flow release track <name>"
 }
@@ -64,16 +65,17 @@ cmd_list() {
 	local current_branch
 	local short_names
 	release_branches=$(echo "$(git_local_branches)" | grep "^$PREFIX")
-	if [ -z "$release_branches" ]; then
+	local remote_release_branches
+	remote_release_branches=$(echo "$(git_remote_branches)" | grep "^$REMOTE_PREFIX")
+	if [ -z "$release_branches" ] && [ -z "$remote_release_branches" ]; then
 		warn "No release branches exist."
                 warn ""
                 warn "You can start a new release branch:"
                 warn ""
-                warn "    git-flow release start <name> [<base>]"
+                warn "    git-flow release start <major/minor> [<base>]"
                 warn ""
 		exit 0
 	fi
-
 	current_branch=$(git branch --no-color | grep '^\* ' | grep -v 'no branch' | sed 's/^* //g')
 	short_names=$(echo "$release_branches" | sed "s ^$PREFIX  g")
 
@@ -84,32 +86,49 @@ cmd_list() {
 		local len=${#branch}
 		width=$(max $width $len)
 	done
+	for branch in $remote_release_branches; do
+		local len=${#branch}
+		width=$(max $width $len)
+	done
 	width=$(($width+3))
 
-	local branch
-	for branch in $short_names; do
-		local fullname=$PREFIX$branch
-		local base=$(git merge-base "$fullname" "$DEVELOP_BRANCH")
-		local develop_sha=$(git rev-parse "$DEVELOP_BRANCH")
-		local branch_sha=$(git rev-parse "$fullname")
-		if [ "$fullname" = "$current_branch" ]; then
-			printf "* "
-		else
-			printf "  "
-		fi
-		if flag verbose; then
-			printf "%-${width}s" "$branch"
-			if [ "$branch_sha" = "$develop_sha" ]; then
-				printf "(no commits yet)"
-			else
-				local nicename=$(git rev-parse --short "$base")
-				printf "(based on $nicename)"
-			fi
-		else
-			printf "%s" "$branch"
-		fi
+	if [ "$release_branches" ]; then
+		printf "Local release branches:"
 		echo
-	done
+		local branch
+		for branch in $short_names; do
+			local fullname=$PREFIX$branch
+			local base=$(git merge-base "$fullname" "$DEVELOP_BRANCH")
+			local develop_sha=$(git rev-parse "$DEVELOP_BRANCH")
+			local branch_sha=$(git rev-parse "$fullname")
+			if [ "$fullname" = "$current_branch" ]; then
+				printf "* "
+			else
+				printf "  "
+			fi
+			if flag verbose; then
+				printf "%-${width}s" "$branch"
+				if [ "$branch_sha" = "$develop_sha" ]; then
+					printf "(no commits yet)"
+				else
+					local nicename=$(git rev-parse --short "$base")
+					printf "(based on $nicename)"
+				fi
+			else
+				printf "%s" "$PREFIX$branch"
+			fi
+			echo
+		done
+	fi
+	if [ "$remote_release_branches" ]; then
+		printf "Remote release branches:"
+		echo
+		for branch in $remote_release_branches; do
+			printf "  "
+			printf "%s" "remotes/$branch"
+			echo
+		done
+	fi
 }
 
 cmd_help() {
@@ -124,7 +143,12 @@ parse_args() {
 
 	# read arguments into global variables
 	VERSION=$1
-	BRANCH=$PREFIX$VERSION
+	# check whether the user has already added the version tag prefix or not
+	if { echo "$VERSION" | grep -q "^$VERSION_PREFIX"; } then
+		local len=${#VERSION_PREFIX}
+		VERSION=${VERSION:$len}
+	fi
+	BRANCH=$PREFIX$VERSION_PREFIX$VERSION
 }
 
 require_version_arg() {
@@ -132,6 +156,62 @@ require_version_arg() {
 		warn "Missing argument <version>"
 		usage
 		exit 1
+	fi
+}
+
+require_major_minor_arg() {
+	if [ "$VERSION" != "major" ] && [ "$VERSION" != "minor" ]; then
+		warn "Missing argument <major/minor>"
+		usage
+		exit 1
+	else
+		local majortag=0
+		local minortag=0
+		if [ "$VERSION" == "major" ]; then
+			local tag
+			for tag in $(git_do for-each-ref refs/tags/ --format='%(refname)'); do
+				if { echo "$tag" | grep -q "$VERSION_PREFIX"; } then
+					local len=10+${#VERSION_PREFIX}
+					local shorttag
+					shorttag=${tag:len}
+					local nextdot
+					nextdot=$(expr index "$shorttag" .)
+					((nextdot-=1))
+					shorttag=${shorttag:0:nextdot}
+					if [[ "$shorttag" -gt "$majortag" ]]; then
+						majortag=$shorttag
+					fi
+				fi
+			done
+			((majortag+=1))
+			minortag=0
+		else
+			local tag
+			for tag in $(git_do for-each-ref refs/tags/ --format='%(refname)'); do
+				if { echo "$tag" | grep -q "$VERSION_PREFIX"; } then
+					local len=10+${#VERSION_PREFIX}
+					local shorttag
+					shorttag=${tag:len}
+					local nextdot
+					nextdot=$(expr index "$shorttag" .)
+					((nextdot-=1))
+					local fronttag=${shorttag:0:nextdot}
+					if [ "$fronttag" -ge "$majortag" ]; then
+						majortag=$fronttag
+						shorttag=${shorttag: ((nextdot+=1))}
+						nextdot=$(expr index "$shorttag" .)
+						((nextdot-=1))
+						shorttag=${shorttag:0:nextdot}
+						if [[ "$shorttag" -gt "$minortag" ]]; then
+							minortag=$shorttag
+						fi
+					fi
+				fi
+			done
+			((minortag+=1))
+		fi
+		VERSION=$majortag.$minortag.0
+		BRANCH=$PREFIX$VERSION_PREFIX$VERSION
 	fi
 }
 
@@ -155,8 +235,9 @@ cmd_start() {
 	DEFINE_boolean fetch false "fetch from $ORIGIN before performing finish" F
 	parse_args "$@"
 	BASE=${2:-$DEVELOP_BRANCH}
-	require_version_arg
-	require_base_is_on_develop
+#	require_version_arg
+	require_major_minor_arg
+#	require_base_is_on_develop
 	require_no_existing_release_branches
 
 	# sanity checks
@@ -164,40 +245,48 @@ cmd_start() {
 	require_branch_absent "$BRANCH"
 	require_tag_absent "$VERSION_PREFIX$VERSION"
 	if flag fetch; then
-		git_do fetch -q "$ORIGIN" "$DEVELOP_BRANCH"
+		git_do fetch -q "$ORIGIN" "$DEVELOP_BRANCH" >/dev/null 2>&1
 	fi
+	# if the origin branch counterpart exists, assert that the local branch
+	# isn't behind it (to avoid unnecessary rebasing)
 	if has "$ORIGIN/$DEVELOP_BRANCH" $(git_remote_branches); then
 		require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
 	fi
 
-	# create branch
-	git_do checkout -b "$BRANCH" "$BASE"
+	# create the local branch and the corresponding remote branch
+	if ! git_do checkout -b "$BRANCH" "$BASE" >/dev/null 2>&1; then
+		die "Could not create hotfix branch '$BRANCH'"
+	else
+		git_do push origin "$BRANCH" >/dev/null 2>&1
+	fi
 
 	echo
 	echo "Summary of actions:"
-	echo "- A new branch '$BRANCH' was created, based on '$BASE'"
+	echo "- A new local branch '$BRANCH' was created, based on '$BASE'"
+	echo "- A new remote branch '$BRANCH' was created, based on the local one"
 	echo "- You are now on branch '$BRANCH'"
 	echo
-	echo "Follow-up actions:"
-	echo "- Bump the version number now!"
-	echo "- Start committing last-minute fixes in preparing your release"
-	echo "- When done, run:"
+#	echo "Follow-up actions:"
+#	echo "- Bump the version number now!"
+#	echo "- Start committing last-minute fixes in preparing your release"
+#	echo "- When done, run:"
+	echo "Now, start committing on the release version. When done, use:"
 	echo
-	echo "     git-flow release finish '$VERSION'"
+	echo "     git-flow release finish $VERSION_PREFIX$VERSION"
 	echo
 }
 
 cmd_finish() {
-	DEFINE_boolean fetch false "fetch from $ORIGIN before performing finish" F
+	DEFINE_boolean fetch true "fetch from $ORIGIN before performing finish" F
 	DEFINE_boolean sign false "sign the release tag cryptographically" s
 	DEFINE_string signingkey "" "use the given GPG-key for the digital signature (implies -s)" u
 	DEFINE_string message "" "use the given tag message" m
 	DEFINE_string messagefile "" "use the contents of the given file as a tag message" f
-	DEFINE_boolean push false "push to $ORIGIN after performing finish" p
+	DEFINE_boolean push true "push to $ORIGIN after performing finish" p
 	DEFINE_boolean keep false "keep branch after performing finish" k
 	DEFINE_boolean notag false "don't tag this release" n
 	DEFINE_boolean squash false "squash release during merge" S
-
+	DEFINE_boolean onlymaster false "merge the current release branch only into the master branch" o
 	parse_args "$@"
 	require_version_arg
 
@@ -209,34 +298,20 @@ cmd_finish() {
 	# sanity checks
 	require_branch "$BRANCH"
 	require_clean_working_tree
-	if flag fetch; then
-		git_do fetch -q "$ORIGIN" "$MASTER_BRANCH" || \
-		  die "Could not fetch $MASTER_BRANCH from $ORIGIN."
-		git_do fetch -q "$ORIGIN" "$DEVELOP_BRANCH" || \
-		  die "Could not fetch $DEVELOP_BRANCH from $ORIGIN."
+	if has "$ORIGIN/$BRANCH" $(git_remote_branches); then
+		if flag fetch; then
+			git_do fetch -q "$ORIGIN" "$MASTER_BRANCH" >/dev/null 2>&1 || \
+			  die "Could not fetch $MASTER_BRANCH from $ORIGIN."
+			git_do fetch -q "$ORIGIN" "$BRANCH" >/dev/null 2>&1 || \
+			  die "Could not fetch $BRANCH from $ORIGIN."
+		fi
 	fi
+
 	if has "$ORIGIN/$MASTER_BRANCH" $(git_remote_branches); then
 		require_branches_equal "$MASTER_BRANCH" "$ORIGIN/$MASTER_BRANCH"
 	fi
-	if has "$ORIGIN/$DEVELOP_BRANCH" $(git_remote_branches); then
-		require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
-	fi
-
-	# try to merge into master
-	# in case a previous attempt to finish this release branch has failed,
-	# but the merge into master was successful, we skip it now
-	if ! git_is_branch_merged_into "$BRANCH" "$MASTER_BRANCH"; then
-		git_do checkout "$MASTER_BRANCH" || \
-		  die "Could not check out $MASTER_BRANCH."
-		if noflag squash; then
-			git_do merge --no-ff "$BRANCH" || \
-				die "There were merge conflicts."
-				# TODO: What do we do now?
-		else
-			git_do merge --squash "$BRANCH" || \
-				die "There were merge conflicts."
-			git_do commit
-		fi
+	if has "$ORIGIN/BRANCH" $(git_remote_branches); then
+		require_branches_equal "$BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
 	fi
 
 	if noflag notag; then
@@ -250,69 +325,100 @@ cmd_finish() {
 			[ "$FLAGS_signingkey" != "" ] && opts="$opts -u '$FLAGS_signingkey'"
 			[ "$FLAGS_message" != "" ] && opts="$opts -m '$FLAGS_message'"
 			[ "$FLAGS_messagefile" != "" ] && opts="$opts -F '$FLAGS_messagefile'"
-			eval git_do tag $opts "$tagname" "$BRANCH" || \
+			eval git_do tag $opts "$tagname" "$BRANCH" >/dev/null 2>&1 || \
 			die "Tagging failed. Please run finish again to retry."
 		fi
 	fi
 
-	# try to merge into develop
-	# in case a previous attempt to finish this release branch has failed,
-	# but the merge into develop was successful, we skip it now
-	if ! git_is_branch_merged_into "$BRANCH" "$DEVELOP_BRANCH"; then
-		git_do checkout "$DEVELOP_BRANCH" || \
-		  die "Could not check out $DEVELOP_BRANCH."
+	if ! flag onlymaster; then
+		# try to merge into develop
+		# in case a previous attempt to finish this release branch has failed,
+		# but the merge into develop was successful, we skip it now
+		git_do fetch -q "$ORIGIN" "$DEVELOP_BRANCH" >/dev/null 2>&1 || \
+		  die "Could not fetch $DEVELOP_BRANCH from $ORIGIN."
+		if ! git_is_branch_merged_into "$BRANCH" "$ORIGIN/$DEVELOP_BRANCH"; then
+			git_do checkout "$DEVELOP_BRANCH" >/dev/null 2>&1 || \
+			  die "Could not check out $DEVELOP_BRANCH."
 
-		# TODO: Actually, accounting for 'git describe' pays, so we should
-		# ideally git merge --no-ff $tagname here, instead!
+			# TODO: Actually, accounting for 'git describe' pays, so we should
+			# ideally git merge --no-ff $tagname here, instead!
+			if noflag squash; then
+				git_do merge --no-ff "$BRANCH" >/dev/null 2>&1 || \
+				  die "There were merge conflicts."
+				  # TODO: What do we do now?
+			else
+				git_do merge --squash "$BRANCH" >/dev/null 2>&1 || \
+				  die "There were merge conflicts."
+				  # TODO: What do we do now?
+				git_do commit >/dev/null 2>&1 
+			fi
+			git_do push "$ORIGIN" "$DEVELOP_BRANCH" >/dev/null 2>&1 || \
+			  die "Could not push to $DEVELOP_BRANCH from $ORIGIN."
+			git_do checkout "$BRANCH" >/dev/null 2>&1 || \
+			  die "Could not check out $BRANCH."
+		fi
+	fi
+
+	# try to merge into master
+	# in case a previous attempt to finish this release branch has failed,
+	# but the merge into master was successful, we skip it now
+	if ! git_is_branch_merged_into "$BRANCH" "$MASTER_BRANCH"; then
+		git_do checkout "$MASTER_BRANCH" >/dev/null 2>&1  || \
+		  die "Could not check out $MASTER_BRANCH."
 		if noflag squash; then
-			git_do merge --no-ff "$BRANCH" || \
+			git_do merge --no-ff "$BRANCH" >/dev/null 2>&1  || \
 				die "There were merge conflicts."
 				# TODO: What do we do now?
 		else
-			git_do merge --squash "$BRANCH" || \
+			git_do merge --squash "$BRANCH" >/dev/null 2>&1 || \
 				die "There were merge conflicts."
-				# TODO: What do we do now?
-			git_do commit
+			git_do commit >/dev/null 2>&1 
 		fi
+	fi
+
+	if flag push; then
+		git_do push "$ORIGIN" "$MASTER_BRANCH" >/dev/null 2>&1 || \
+			die "Could not push to $MASTER_BRANCH from $ORIGIN."
+		if noflag notag; then
+			git_do push --tags "$ORIGIN" >/dev/null 2>&1 || \
+			  die "Could not push tags to $ORIGIN."
+		fi
+		git_do push "$ORIGIN" :"$BRANCH" >/dev/null 2>&1 || \
+			die "Could not delete the remote $BRANCH in $ORIGIN."
 	fi
 
 	# delete branch
 	if noflag keep; then
-		if [ "$BRANCH" = "$(git_current_branch)" ]; then
-			git_do checkout "$MASTER_BRANCH"
-		fi
-		git_do branch -d "$BRANCH"
-	fi
-
-	if flag push; then
-		git_do push "$ORIGIN" "$DEVELOP_BRANCH" || \
-			die "Could not push to $DEVELOP_BRANCH from $ORIGIN."
-		git_do push "$ORIGIN" "$MASTER_BRANCH" || \
-			die "Could not push to $MASTER_BRANCH from $ORIGIN."
-		if noflag notag; then
-			git_do push --tags "$ORIGIN" || \
-			  die "Could not push tags to $ORIGIN."
-		fi
-		git_do push "$ORIGIN" :"$BRANCH" || \
-			die "Could not delete the remote $BRANCH in $ORIGIN."
+		git_do checkout "$DEVELOP_BRANCH" >/dev/null 2>&1 || \
+		  die "Could not check out $BRANCH."
+		git_do branch -d "$BRANCH" >/dev/null 2>&1
+		git_do push "$ORIGIN" ":refs/heads/$BRANCH" >/dev/null 2>&1
 	fi
 
 	echo
 	echo "Summary of actions:"
 	echo "- Latest objects have been fetched from '$ORIGIN'"
 	echo "- Release branch has been merged into '$MASTER_BRANCH'"
-	if noflag notag; then
+#	if noflag notag; then
 		echo "- The release was tagged '$tagname'"
+#	fi
+	if ! flag onlymaster; then
+		echo "- Release branch has been back-merged into '$DEVELOP_BRANCH'"
 	fi
-	echo "- Release branch has been back-merged into '$DEVELOP_BRANCH'"
 	if flag keep; then
-		echo "- Release branch '$BRANCH' is still available"
+		echo "- Release branch '$BRANCH' (local and remote) is still available"
 	else
-		echo "- Release branch '$BRANCH' has been deleted"
+		echo "- Release branch '$BRANCH' (local and remote) has been deleted"
 	fi
 	if flag push; then
-		echo "- '$DEVELOP_BRANCH', '$MASTER_BRANCH' and tags have been pushed to '$ORIGIN'"
-		echo "- Release branch '$BRANCH' in '$ORIGIN' has been deleted."
+		if ! flag onlymaster; then
+			echo "- '$DEVELOP_BRANCH', '$MASTER_BRANCH' and tags have been pushed to '$ORIGIN'"
+		else
+			echo "- '$MASTER_BRANCH' and tags have been pushed to '$ORIGIN'"
+		fi
+	fi
+	if noflag keep; then
+		echo "- You are now on branch '$DEVELOP_BRANCH'"
 	fi
 	echo
 }
@@ -340,6 +446,7 @@ cmd_publish() {
 	echo "Summary of actions:"
 	echo "- A new remote branch '$BRANCH' was created"
 	echo "- The local branch '$BRANCH' was configured to track the remote branch"
+	echo "- The old remote branch '$BRANCH' has to be deleted manually"
 	echo "- You are now on branch '$BRANCH'"
 	echo
 }
