Bug fixing

diff --git a/git-flow-feature b/git-flow-feature
--- a/git-flow-feature
+++ b/git-flow-feature
@@ -201,6 +201,35 @@ parse_args() {
 	FLAGS "$@" || exit $?
 	eval set -- "${FLAGS_ARGV}"
 
+	# process possible trailing arguments
+	length_old=0
+	for k in "${@:2}"
+	do
+		length_old=$[$length_old+1]
+	done
+	if [ "$length_old" -gt "0" ]; then
+		FLAGS "${@:2}" || exit $?
+		length_new=0
+		for l in ${FLAGS_ARGV[@]}
+		do
+			length_new=$[$length_new+1]
+		done
+		if [ "$length_new" -gt "0" ] && [ "$length_new" != "$length_old" ]; then
+			die "Putting flags between the two main arguments is not a good idea! Process aborted."
+		fi
+		if [ "$length_new" == "$length_old" ]; then
+			FLAGS "${@:3}" || exit $?
+			length_newnew=0
+			for l in ${FLAGS_ARGV[@]}
+			do
+				length_newnew=$[$length_newnew+1]
+			done
+			if [ "$length_newnew" == "$length_old" ]; then
+				die "Too many arguments have been found!"
+			fi
+		fi
+	fi
+
 	# read arguments into global variables
 	NAME=$1
 	BRANCH=$PREFIX$NAME
@@ -210,6 +239,35 @@ parse_remote_name() {
 	# parse options
 	FLAGS "$@" || exit $?
 	eval set -- "${FLAGS_ARGV}"
+
+	# process possible trailing arguments
+	length_old=0
+	for k in "${@:2}"
+	do
+		length_old=$[$length_old+1]
+	done
+	if [ "$length_old" -gt "0" ]; then
+		FLAGS "${@:2}" || exit $?
+		length_new=0
+		for l in ${FLAGS_ARGV[@]}
+		do
+			length_new=$[$length_new+1]
+		done
+		if [ "$length_new" -gt "0" ] && [ "$length_new" != "$length_old" ]; then
+			die "Putting flags between the two main arguments is not a good idea! Process aborted."
+		fi
+		if [ "$length_new" == "$length_old" ]; then
+			FLAGS "${@:3}" || exit $?
+			length_newnew=0
+			for l in ${FLAGS_ARGV[@]}
+			do
+				length_newnew=$[$length_newnew+1]
+			done
+			if [ "$length_newnew" == "$length_old" ]; then
+				die "Too many arguments have been found!"
+			fi
+		fi
+	fi
 
 	# read arguments into global variables
 	REMOTE=$1
@@ -227,6 +285,7 @@ cmd_start() {
 	require_branch_absent "$BRANCH"
 	git_do remote update >/dev/null 2>&1 || \
 	  die "Could not update remote branches from $ORIGIN."
+	git_do remote prune origin >/dev/null 2>&1
 	require_branch_absent "$ORIGIN/$BRANCH"
 
 	# update the local repo with remote changes, if asked
@@ -251,7 +310,7 @@ cmd_start() {
 	if ! git_do checkout -b "$BRANCH" "$BASE" >/dev/null 2>&1; then
 		die "Could not create feature branch '$BRANCH'"
 	else
-		git_do push origin "$BRANCH" >/dev/null 2>&1 || \
+		git_do push -u origin "$BRANCH" >/dev/null 2>&1 || \
 		  die "Could not push to $BRANCH from $ORIGIN."
 	fi
 
@@ -282,6 +341,7 @@ cmd_finish() {
 	  die "Could not check out $BRANCH."
 	git_do fetch -q "$ORIGIN" "$BRANCH" >/dev/null 2>&1 || \
 	  die "Could not fetch $BRANCH from $ORIGIN."
+	git_do remote prune origin >/dev/null 2>&1
 	require_branch "$ORIGIN/$BRANCH"
 	git_do merge --no-commit "$ORIGIN/$BRANCH" >/dev/null 2>&1 || \
 	  die "There were merge conflicts on $BRANCH. Resolve them using git mergetool."
@@ -376,7 +436,7 @@ cmd_finish() {
 		    git_do merge --no-ff "$BRANCH" >/dev/null 2>&1
 		else
 			git_do merge --squash "$BRANCH" >/dev/null 2>&1
-			git_do commit >/dev/null 2>&1
+			git_do commit --quiet
 			git_do merge "$BRANCH" >/dev/null 2>&1
 		fi
 	fi
@@ -408,7 +468,7 @@ helper_finish_cleanup() {
 
 	# push branches to origin
 	if flag fetch; then
-		git_do push "$ORIGIN" ":refs/heads/$BRANCH" >/dev/null 2>&1 || \
+		git_do push "$ORIGIN" "$BRANCH" >/dev/null 2>&1 || \
 		  die "Could not push to $BRANCH from $ORIGIN."
 		git_do push "$ORIGIN" "$DEVELOP_BRANCH" >/dev/null 2>&1 || \
 		  die "Could not push to $DEVELOP_BRANCH from $ORIGIN."
@@ -416,7 +476,8 @@ helper_finish_cleanup() {
 	
 	# delete branch
 	if noflag keep; then
-		git_do push origin ":$BRANCH" >/dev/null 2>&1
+		git_do push origin ":$BRANCH" >/dev/null 2>&1 || \
+		  die "Could not delete the remote $BRANCH in $ORIGIN."
 		if flag force_delete; then
 			git_do branch -D "$BRANCH" >/dev/null 2>&1
 		else
@@ -452,15 +513,24 @@ cmd_delete() {
 	git_do branch -D "$BRANCH" >/dev/null 2>&1
 
 	if ! flag local; then
-		# delete remote branch
-		git_do push "$ORIGIN" ":refs/heads/$BRANCH" >/dev/null 2>&1
+		# make sure that the remote branch should be deleted as well
+		read -p "Are you sure that you want to delete the remote branch as well (Y/N)? " answer
+		if [ "$answer" == "y" ] || [ "$answer" == "Y" ] || [ "$answer" == "yes" ] || [ "$answer" == "Yes" ] || [ "$answer" == "YES" ]; then
+			# delete remote branch
+#			git_do remote prune origin >/dev/null 2>&1
+			git_do push "$ORIGIN" ":refs/heads/$BRANCH" >/dev/null 2>&1
+		else
+			answer="false"
+		fi
 	fi
 
 	echo
 	echo "Summary of actions:"
 	echo "- The local branch '$BRANCH' has been deleted"
 	if ! flag local; then
-		echo "- The remote branch '$ORIGIN/$BRANCH' has been deleted"
+		if [ "$answer" != "false" ]; then
+			echo "- The remote branch '$ORIGIN/$BRANCH' has been deleted"
+		fi
 	fi
 	echo "- You are now on branch '$DEVELOP_BRANCH'"
 	echo
@@ -475,6 +545,7 @@ cmd_publish() {
 	require_branch "$BRANCH"
 	git_do fetch -q "$ORIGIN" >/dev/null 2>&1 || \
 	  die "Could not fetch from $ORIGIN."
+	git_do remote prune origin >/dev/null 2>&1
 	require_branch_absent "$ORIGIN/$BRANCH"
 
 	# create remote branch
@@ -503,8 +574,9 @@ cmd_track() {
 	# sanity checks
 	require_clean_working_tree
 	require_branch_absent "$BRANCH"
-	git_do fetch -q "$ORIGIN"  >/dev/null 2>&1 || \
+	git_do fetch -q "$ORIGIN" >/dev/null 2>&1 || \
 	  die "Could not fetch from $ORIGIN."
+	git_do remote prune origin >/dev/null 2>&1
 	require_branch "$ORIGIN/$BRANCH"
 
 	# create tracking branch
@@ -639,6 +711,7 @@ cmd_update() {
 
 	git_do checkout "$base" >/dev/null 2>&1 || \
 	  die "Could not check out $base."
+	git_do remote prune origin >/dev/null 2>&1
 	git_do fetch -q "$ORIGIN" "$base" >/dev/null 2>&1 || \
 	  die "Could not fetch $base from $ORIGIN."
 	git_do merge --no-commit "$ORIGIN/$base" >/dev/null 2>&1  || \
diff --git a/git-flow-hotfix b/git-flow-hotfix
--- a/git-flow-hotfix
+++ b/git-flow-hotfix
@@ -151,6 +151,35 @@ parse_args() {
 	FLAGS "$@" || exit $?
 	eval set -- "${FLAGS_ARGV}"
 
+	# process possible trailing arguments
+	length_old=0
+	for k in "${@:2}"
+	do
+		length_old=$[$length_old+1]
+	done
+	if [ "$length_old" -gt "0" ]; then
+		FLAGS "${@:2}" || exit $?
+		length_new=0
+		for l in ${FLAGS_ARGV[@]}
+		do
+			length_new=$[$length_new+1]
+		done
+		if [ "$length_new" -gt "0" ] && [ "$length_new" != "$length_old" ]; then
+			die "Putting flags between the two main arguments is not a good idea! Process aborted."
+		fi
+		if [ "$length_new" == "$length_old" ]; then
+			FLAGS "${@:3}" || exit $?
+			length_newnew=0
+			for l in ${FLAGS_ARGV[@]}
+			do
+				length_newnew=$[$length_newnew+1]
+			done
+			if [ "$length_newnew" == "$length_old" ]; then
+				die "Too many arguments have been found!"
+			fi
+		fi
+	fi
+
 	# read arguments into global variables
 	VERSION=$1
 	# check whether the user has already added the version tag prefix or not
@@ -248,6 +277,7 @@ cmd_start() {
 	require_branch_absent "$NEW_BRANCH"
 	git_do remote update >/dev/null 2>&1 || \
 	  die "Could not update remote branches from $ORIGIN."
+	git_do remote prune origin >/dev/null 2>&1
 	if has $ORIGIN/$NEW_BRANCH $(git_all_branches); then
 		die "There is an existing hotfix branch ($ORIGIN/$NEW_BRANCH). Finish that one first."
 	fi
@@ -272,7 +302,7 @@ cmd_start() {
 	if ! git_do checkout -b "$NEW_BRANCH" "$VERSION_PREFIX$VERSION" >/dev/null 2>&1; then
 		die "Could not create hotfix branch '$NEW_BRANCH'"
 	else
-		git_do push origin "$NEW_BRANCH" >/dev/null 2>&1
+		git_do push -u origin "$NEW_BRANCH" >/dev/null 2>&1
 	fi
 
 	echo
@@ -299,7 +329,8 @@ cmd_publish() {
 	require_clean_working_tree
 	require_branch "$BRANCH"
 	git_do fetch -q "$ORIGIN" >/dev/null 2>&1 || \
-	  die "Could not fetch from $ORIGIN
+	  die "Could not fetch from $ORIGIN."
+	git_do remote prune origin >/dev/null 2>&1
 	require_branch_absent "$ORIGIN/$BRANCH"
 
 	# create remote branch
@@ -328,8 +359,9 @@ cmd_track() {
 	# sanity checks
 	require_clean_working_tree
 	require_branch_absent "$BRANCH"
-	git_do fetch -q "$ORIGIN"  >/dev/null 2>&1 || \
-	  die "Could not fetch from $OR
+	git_do fetch -q "$ORIGIN" >/dev/null 2>&1 || \
+	  die "Could not fetch from $ORIGIN."
+	git_do remote prune origin >/dev/null 2>&1
 	require_branch "$ORIGIN/$BRANCH"
 
 	# create tracking branch
@@ -368,6 +400,7 @@ cmd_finish() {
 	  die "Could not check out $BRANCH."
 	git_do fetch -q "$ORIGIN" "$BRANCH" >/dev/null 2>&1 || \
 	  die "Could not fetch $BRANCH from $ORIGIN."
+	git_do remote prune origin >/dev/null 2>&1
 	require_branch "$ORIGIN/$BRANCH"
 	git_do merge --no-commit "$ORIGIN/$BRANCH" >/dev/null 2>&1 || \
 	  die "There were merge conflicts on $BRANCH. Resolve them using git mergetool."
@@ -529,7 +562,7 @@ cmd_finish() {
 ##		  die "Could not check out $MASTER_BRANCH."
 ##		git_do checkout "$previoustag" >/dev/null 2>&1 || \
 ##		  die "Could not check out $previoustag."
-##		git_do commit --amend -v >/dev/null 2>&1 || \
+##		git_do commit --amend -v --quiet || \
 ##		  die "There were merge conflicts."
 ##		  # TODO: What do we do now?
 #		git_do merge --no-ff "$MASTER_BRANCH" >/dev/null 2>&1 || \
@@ -561,7 +594,8 @@ cmd_finish() {
 		  die "Could not check out $BRANCH."
 #		git_do branch -d "$BRANCH" >/dev/null 2>&1
 		git_do branch -D "$BRANCH" >/dev/null 2>&1
-		git_do push "$ORIGIN" ":refs/heads/$BRANCH" >/dev/null 2>&1
+		git_do push "$ORIGIN" ":refs/heads/$BRANCH" >/dev/null 2>&1 || \
+		  die "Could not delete the remote $BRANCH in $ORIGIN."
 	fi
 
 	echo
@@ -619,15 +653,24 @@ cmd_delete() {
 	git_do branch -D "$BRANCH" >/dev/null 2>&1
 
 	if ! flag local; then
-		# delete remote branch
-		git_do push "$ORIGIN" ":refs/heads/$BRANCH" >/dev/null 2>&1
+		# make sure that the remote branch should be deleted as well
+		read -p "Are you sure that you want to delete the remote branch as well (Y/N)? " answer
+		if [ "$answer" == "y" ] || [ "$answer" == "Y" ] || [ "$answer" == "yes" ] || [ "$answer" == "Yes" ] || [ "$answer" == "YES" ]; then
+			# delete remote branch
+#			git_do remote prune origin >/dev/null 2>&1
+			git_do push "$ORIGIN" ":refs/heads/$BRANCH" >/dev/null 2>&1
+		else
+			answer="false"
+		fi
 	fi
 
 	echo
 	echo "Summary of actions:"
 	echo "- The local branch '$BRANCH' has been deleted"
 	if ! flag local; then
-		echo "- The remote branch '$ORIGIN/$BRANCH' has been deleted"
+		if [ "$answer" != "false" ]; then
+			echo "- The remote branch '$ORIGIN/$BRANCH' has been deleted"
+		fi
 	fi
 	echo "- You are now on branch '$DEVELOP_BRANCH'"
 	echo
diff --git a/git-flow-release b/git-flow-release
--- a/git-flow-release
+++ b/git-flow-release
@@ -145,6 +145,35 @@ parse_args() {
 	FLAGS "$@" || exit $?
 	eval set -- "${FLAGS_ARGV}"
 
+	# process possible trailing arguments
+	length_old=0
+	for k in "${@:2}"
+	do
+		length_old=$[$length_old+1]
+	done
+	if [ "$length_old" -gt "0" ]; then
+		FLAGS "${@:2}" || exit $?
+		length_new=0
+		for l in ${FLAGS_ARGV[@]}
+		do
+			length_new=$[$length_new+1]
+		done
+		if [ "$length_new" -gt "0" ] && [ "$length_new" != "$length_old" ]; then
+			die "Putting flags between the two main arguments is not a good idea! Process aborted."
+		fi
+		if [ "$length_new" == "$length_old" ]; then
+			FLAGS "${@:3}" || exit $?
+			length_newnew=0
+			for l in ${FLAGS_ARGV[@]}
+			do
+				length_newnew=$[$length_newnew+1]
+			done
+			if [ "$length_newnew" == "$length_old" ]; then
+				die "Too many arguments have been found!"
+			fi
+		fi
+	fi
+
 	# read arguments into global variables
 	VERSION=$1
 	# check whether the user has already added the version tag prefix or not
@@ -260,6 +289,7 @@ cmd_start() {
 	require_branch_absent "$BRANCH"
 	git_do remote update >/dev/null 2>&1 || \
 	  die "Could not update remote branches from $ORIGIN."
+	git_do remote prune origin >/dev/null 2>&1
 	require_no_existing_remote_release_branches
 #	require_branch_absent "$ORIGIN/$BRANCH"
 	require_tag_absent "$VERSION_PREFIX$VERSION"
@@ -283,7 +313,7 @@ cmd_start() {
 	if ! git_do checkout -b "$BRANCH" "$DEVELOP_BRANCH" >/dev/null 2>&1; then
 		die "Could not create release branch '$BRANCH'"
 	else
-		git_do push origin "$BRANCH" >/dev/null 2>&1
+		git_do push -u origin "$BRANCH" >/dev/null 2>&1
 	fi
 
 	echo
@@ -328,6 +358,7 @@ cmd_finish() {
 	  die "Could not check out $BRANCH."
 	git_do fetch -q "$ORIGIN" "$BRANCH" >/dev/null 2>&1 || \
 	  die "Could not fetch $BRANCH from $ORIGIN."
+	git_do remote prune origin >/dev/null 2>&1
 	require_branch "$ORIGIN/$BRANCH"
 	git_do merge --no-commit "$ORIGIN/$BRANCH" >/dev/null 2>&1 || \
 	  die "There were merge conflicts on $BRANCH. Resolve them using git mergetool."
@@ -367,7 +398,7 @@ cmd_finish() {
 			[ "$FLAGS_signingkey" != "" ] && opts="$opts -u '$FLAGS_signingkey'"
 			[ "$FLAGS_message" != "" ] && opts="$opts -m '$FLAGS_message'"
 			[ "$FLAGS_messagefile" != "" ] && opts="$opts -F '$FLAGS_messagefile'"
-			eval git_do tag $opts "$tagname" "$BRANCH" >/dev/null 2>&1 || \
+			eval git_do tag $opts "$tagname" "$BRANCH" || \
 			  die "Tagging failed. Please run finish again to retry."
 		fi
 	fi
@@ -397,7 +428,7 @@ cmd_finish() {
 				git_do merge --squash "$BRANCH" >/dev/null 2>&1 || \
 				  die "There were merge conflicts."
 				  # TODO: What do we do now?
-				git_do commit >/dev/null 2>&1 
+				git_do commit --quiet 
 			fi
 			git_do push "$ORIGIN" "$DEVELOP_BRANCH" >/dev/null 2>&1 || \
 			  die "Could not push to $DEVELOP_BRANCH from $ORIGIN."
@@ -419,7 +450,7 @@ cmd_finish() {
 		else
 			git_do merge --squash "$BRANCH" >/dev/null 2>&1 || \
 				die "There were merge conflicts."
-			git_do commit >/dev/null 2>&1 
+			git_do commit --quiet 
 		fi
 	fi
 
@@ -430,8 +461,8 @@ cmd_finish() {
 			git_do push --tags "$ORIGIN" >/dev/null 2>&1 || \
 			  die "Could not push tags to $ORIGIN."
 		fi
-		git_do push "$ORIGIN" :"$BRANCH" >/dev/null 2>&1 || \
-			die "Could not delete the remote $BRANCH in $ORIGIN."
+#		git_do push "$ORIGIN" :"$BRANCH" >/dev/null 2>&1 || \
+#			die "Could not delete the remote $BRANCH in $ORIGIN."
 	fi
 
 	# delete branch
@@ -439,7 +470,8 @@ cmd_finish() {
 		git_do checkout "$DEVELOP_BRANCH" >/dev/null 2>&1 || \
 		  die "Could not check out $BRANCH."
 		git_do branch -d "$BRANCH" >/dev/null 2>&1
-		git_do push "$ORIGIN" ":refs/heads/$BRANCH" >/dev/null 2>&1
+		git_do push "$ORIGIN" ":refs/heads/$BRANCH" >/dev/null 2>&1 || \
+		  die "Could not delete the remote $BRANCH in $ORIGIN."
 	fi
 
 	echo
@@ -478,6 +510,7 @@ cmd_publish() {
 	require_clean_working_tree
 	require_branch "$BRANCH"
 	git_do fetch -q "$ORIGIN" >/dev/null 2>&1
+	git_do remote prune origin >/dev/null 2>&1
 	require_branch_absent "$ORIGIN/$BRANCH"
 
 	# create remote branch
@@ -505,7 +538,9 @@ cmd_track() {
 	# sanity checks
 	require_clean_working_tree
 	require_branch_absent "$BRANCH"
-	git_do fetch -q "$ORIGIN" >/dev/null 2>&1
+	git_do fetch -q "$ORIGIN" >/dev/null 2>&1 || \
+	  die "Could not fetch from $ORIGIN."
+	git_do remote prune origin >/dev/null 2>&1
 	require_branch "$ORIGIN/$BRANCH"
 
 	# create tracking branch
@@ -533,15 +568,24 @@ cmd_delete() {
 	git_do branch -D "$BRANCH" >/dev/null 2>&1
 
 	if ! flag local; then
-		# delete remote branch
-		git_do push "$ORIGIN" ":refs/heads/$BRANCH" >/dev/null 2>&1
+		# make sure that the remote branch should be deleted as well
+		read -p "Are you sure that you want to delete the remote branch as well (Y/N)? " answer
+		if [ "$answer" == "y" ] || [ "$answer" == "Y" ] || [ "$answer" == "yes" ] || [ "$answer" == "Yes" ] || [ "$answer" == "YES" ]; then
+			# delete remote branch
+#			git_do remote prune origin >/dev/null 2>&1
+			git_do push "$ORIGIN" ":refs/heads/$BRANCH" >/dev/null 2>&1
+		else
+			answer="false"
+		fi
 	fi
 
 	echo
 	echo "Summary of actions:"
 	echo "- The local branch '$BRANCH' has been deleted"
 	if ! flag local; then
-		echo "- The remote branch '$ORIGIN/$BRANCH' has been deleted"
+		if [ "$answer" != "false" ]; then
+			echo "- The remote branch '$ORIGIN/$BRANCH' has been deleted"
+		fi
 	fi
 	echo "- You are now on branch '$DEVELOP_BRANCH'"
 	echo
diff --git a/git-flow-support b/git-flow-support
--- a/git-flow-support
+++ b/git-flow-support
@@ -149,6 +149,35 @@ parse_args() {
 	FLAGS "$@" || exit $?
 	eval set -- "${FLAGS_ARGV}"
 
+	# process possible trailing arguments
+	length_old=0
+	for k in "${@:2}"
+	do
+		length_old=$[$length_old+1]
+	done
+	if [ "$length_old" -gt "0" ]; then
+		FLAGS "${@:2}" || exit $?
+		length_new=0
+		for l in ${FLAGS_ARGV[@]}
+		do
+			length_new=$[$length_new+1]
+		done
+		if [ "$length_new" -gt "0" ] && [ "$length_new" != "$length_old" ]; then
+			die "Putting flags between the two main arguments is not a good idea! Process aborted."
+		fi
+		if [ "$length_new" == "$length_old" ]; then
+			FLAGS "${@:3}" || exit $?
+			length_newnew=0
+			for l in ${FLAGS_ARGV[@]}
+			do
+				length_newnew=$[$length_newnew+1]
+			done
+			if [ "$length_newnew" == "$length_old" ]; then
+				die "Too many arguments have been found!"
+			fi
+		fi
+	fi
+
 	# read arguments into global variables
 	VERSION=$1
 	BASE=$2
@@ -203,6 +232,7 @@ cmd_start() {
 	require_branch_absent "$BRANCH"
 	git_do remote update >/dev/null 2>&1 || \
 	  die "Could not update remote branches from $ORIGIN."
+	git_do remote prune origin >/dev/null 2>&1
 	require_branch_absent "$ORIGIN/$BRANCH"
 
 	# if the origin branch counterpart exists, assert that the local branch
@@ -217,7 +247,7 @@ cmd_start() {
 			die "Could not create support branch '$BRANCH'"
 		fi
 	else
-		git_do push origin "$BRANCH" >/dev/null 2>&1
+		git_do push -u origin "$BRANCH" >/dev/null 2>&1
 	fi
 
 	echo
@@ -245,15 +275,24 @@ cmd_delete() {
 	git_do branch -D "$BRANCH" >/dev/null 2>&1
 
 	if ! flag local; then
-		# delete remote branch
-		git_do push "$ORIGIN" ":refs/heads/$BRANCH" >/dev/null 2>&1
+		# make sure that the remote branch should be deleted as well
+		read -p "Are you sure that you want to delete the remote branch as well (Y/N)? " answer
+		if [ "$answer" == "y" ] || [ "$answer" == "Y" ] || [ "$answer" == "yes" ] || [ "$answer" == "Yes" ] || [ "$answer" == "YES" ]; then
+			# delete remote branch
+#			git_do remote prune origin >/dev/null 2>&1
+			git_do push "$ORIGIN" ":refs/heads/$BRANCH" >/dev/null 2>&1
+		else
+			answer="false"
+		fi
 	fi
 
 	echo
 	echo "Summary of actions:"
 	echo "- The local branch '$BRANCH' has been deleted"
 	if ! flag local; then
-		echo "- The remote branch '$ORIGIN/$BRANCH' has been deleted"
+		if [ "$answer" != "false" ]; then
+			echo "- The remote branch '$ORIGIN/$BRANCH' has been deleted"
+		fi
 	fi
 	echo "- You are now on branch '$DEVELOP_BRANCH'"
 	echo
