Tagging a release version after the corresponding release branch has been merged into the master branch

diff --git a/git-flow-release b/git-flow-release
--- a/git-flow-release
+++ b/git-flow-release
@@ -392,22 +392,6 @@ cmd_finish() {
 		require_branches_equal "$BRANCH" "$ORIGIN/$BRANCH"
 	fi
 
-	if noflag notag; then
-		# try to tag the release
-		# in case a previous attempt to finish this release branch has failed,
-		# but the tag was set successful, we skip it now
-		local tagname=$VERSION_PREFIX$VERSION
-		if ! git_tag_exists "$tagname"; then
-			local opts="-a"
-			flag sign && opts="$opts -s"
-			[ "$FLAGS_signingkey" != "" ] && opts="$opts -u '$FLAGS_signingkey'"
-			[ "$FLAGS_message" != "" ] && opts="$opts -m '$FLAGS_message'"
-			[ "$FLAGS_messagefile" != "" ] && opts="$opts -F '$FLAGS_messagefile'"
-			eval git_do tag $opts "$tagname" "$BRANCH" || \
-			  die "Tagging failed. Please run finish again to retry."
-		fi
-	fi
-
 	if ! flag onlymaster; then
 		# try to merge into develop
 		# in case a previous attempt to finish this release branch has failed,
@@ -460,6 +444,22 @@ cmd_finish() {
 			git_do merge --squash "$BRANCH" >/dev/null 2>&1 || \
 				die "There were merge conflicts."
 			git_do commit --quiet 
+		fi
+	fi
+
+	if noflag notag; then
+		# try to tag the release
+		# in case a previous attempt to finish this release branch has failed,
+		# but the tag was set successful, we skip it now
+		local tagname=$VERSION_PREFIX$VERSION
+		if ! git_tag_exists "$tagname"; then
+			local opts="-a"
+			flag sign && opts="$opts -s"
+			[ "$FLAGS_signingkey" != "" ] && opts="$opts -u '$FLAGS_signingkey'"
+			[ "$FLAGS_message" != "" ] && opts="$opts -m '$FLAGS_message'"
+			[ "$FLAGS_messagefile" != "" ] && opts="$opts -F '$FLAGS_messagefile'"
+			eval git_do tag $opts "$tagname" "$MASTER_BRANCH" || \
+			  die "Tagging failed. Please run finish again to retry."
 		fi
 	fi
 
