Now, the Gitflow script package performs all operations formerly done by the script named 'versioned_git_ci'

diff --git a/git-flow-hotfix b/git-flow-hotfix
--- a/git-flow-hotfix
+++ b/git-flow-hotfix
@@ -424,22 +424,6 @@ cmd_finish() {
 		require_branches_equal "$BRANCH" "$ORIGIN/$BRANCH"
 	fi
 
-	if noflag notag; then
-		# try to tag the hotfix
-		# in case a previous attempt to finish this hotfix branch has failed,
-		# but the tag was set successful, we skip it now
-		local tagname=$VERSION_PREFIX$VERSION
-		if ! git_tag_exists "$tagname"; then
-			local opts="-a"
-			flag sign && opts="$opts -s"
-			[ "$FLAGS_signingkey" != "" ] && opts="$opts -u '$FLAGS_signingkey'"
-			[ "$FLAGS_message" != "" ] && opts="$opts -m '$FLAGS_message'"
-			[ "$FLAGS_messagefile" != "" ] && opts="$opts -F '$FLAGS_messagefile'"
-			eval git_do tag $opts "$tagname" "$BRANCH" || \
-			die "Tagging failed. Please run finish again to retry."
-		fi
-	fi
-
 	local norelease=false
 	if ! flag onlyhotfix; then
 #		if flag release; then
@@ -583,6 +567,77 @@ cmd_finish() {
 #		git_do checkout "$BRANCH" >/dev/null 2>&1 || \
 #		  die "Could not check out $BRANCH."
 #	fi
+
+	# if a hotfix version of Pasimodo is finished, some additional versioning tasks have to be performed
+	# (formerly done by the script called "versioned_git_ci")
+	# find the directory named versioning and enter it
+	local level_counter=0
+	local found=0
+	while [ "$found" == 0 ] && [ "$level_counter" -lt "15" ]; do
+		if [ -d "versioning" ]; then
+			cd versioning
+			found=1
+		else
+			cd ..
+			level_counter=$(($level_counter+1))
+		fi
+	done
+	# extract the major, the minor and the hotfix tag of the Pasimodo version to be finished
+	if [ "$found" == 1 ]; then
+		git_do checkout "$BRANCH" >/dev/null 2>&1 || \
+		  die "Could not check out $BRANCH."
+		local majortag=0
+		local minortag=0
+		local hotfixtag=0
+		local shorttag=$VERSION
+		local nextdot
+		nextdot=$(expr index "$shorttag" .)
+		((nextdot-=1))
+		majortag=${shorttag:0:nextdot}
+		shorttag=${shorttag: ((nextdot+=1))}
+		nextdot=$(expr index "$shorttag" .)
+		((nextdot-=1))
+		minortag=${shorttag:0:nextdot}
+		hotfixtag=${shorttag: ((nextdot+=1))}
+		if [ -f "Pasimodo_Version.txt" ]; then
+			echo -e $majortag'\n'$minortag > Pasimodo_Version.txt
+		fi
+		if [ -f "Pasimodo_Revision.txt" ]; then
+			echo -e $hotfixtag > Pasimodo_Revision.txt
+		fi
+		local year=$(date +%Y)
+		local month=$(date +%m)
+		local day=$(date +%d)
+		local hour=$(date +%H)
+		local minute=$(date +%M)
+		local second=$(date +%S)
+		local time="$year/$month/$day $hour:$minute:$second"
+		if [ -f "CMake_Pasimodo_Revision.txt" ]; then
+			echo -e "SET(Pasimodo_MAJOR_VERSION $majortag)\nSET(Pasimodo_MINOR_VERSION $minortag)\nSET(Pasimodo_REVISION_TIME \"$time\")\nSET(Pasimodo_REVISION $hotfixtag)" > CMake_Pasimodo_Revision.txt
+		fi
+		git_do commit --quiet -a -m "Some final modifications before Pasimodo version $VERSION is ready to be released" || \
+		  die "Could not commit changes to local branch $BRANCH."
+		git_do push origin "$BRANCH" >/dev/null 2>&1 || \
+		  die "Could not push to $BRANCH from $ORIGIN."
+	fi
+
+	if noflag notag; then
+		# try to tag the hotfix
+		# in case a previous attempt to finish this hotfix branch has failed,
+		# but the tag was set successful, we skip it now
+		git_do checkout "$BRANCH" >/dev/null 2>&1 || \
+		  die "Could not check out $BRANCH."
+		local tagname=$VERSION_PREFIX$VERSION
+		if ! git_tag_exists "$tagname"; then
+			local opts="-a"
+			flag sign && opts="$opts -s"
+			[ "$FLAGS_signingkey" != "" ] && opts="$opts -u '$FLAGS_signingkey'"
+			[ "$FLAGS_message" != "" ] && opts="$opts -m '$FLAGS_message'"
+			[ "$FLAGS_messagefile" != "" ] && opts="$opts -F '$FLAGS_messagefile'"
+			eval git_do tag $opts "$tagname" "$BRANCH" || \
+			die "Tagging failed. Please run finish again to retry."
+		fi
+	fi
 
 	if flag push; then
 #		git_do push "$ORIGIN" "$MASTER_BRANCH" >/dev/null 2>&1 || \
