Modified git-flow hotfix command to meet the requirements demanded by the new pasimodo branching model

diff --git a/git-flow-hotfix b/git-flow-hotfix
--- a/git-flow-hotfix
+++ b/git-flow-hotfix
@@ -42,12 +42,13 @@ init() {
   gitflow_load_settings
   VERSION_PREFIX=$(eval "echo `git config --get gitflow.prefix.versiontag`")
   PREFIX=$(git config --get gitflow.prefix.hotfix)
+  REMOTE_PREFIX=$ORIGIN/$PREFIX
 }
 
 usage() {
 	echo "usage: git-flow hotfix [list] [-v]"
 	echo "       git-flow hotfix start [-F] <version> [<base>]"
-	echo "       git-flow hotfix finish [-Fsumpk] <version>"
+	echo "       git-flow hotfix finish [-Fsumpkr] <version>"
 	echo "       git-flow hotfix publish <version>"
 	echo "       git-flow hotfix track <version>"
 }
@@ -64,7 +65,9 @@ cmd_list() {
 	local current_branch
 	local short_names
 	hotfix_branches=$(echo "$(git_local_branches)" | grep "^$PREFIX")
-	if [ -z "$hotfix_branches" ]; then
+	local remote_hotfix_branches
+	remote_hotfix_branches=$(echo "$(git_remote_branches)" | grep "^$REMOTE_PREFIX")
+	if [ -z "$hotfix_branches" ] && [ -z "$remote_hotfix_branches" ]; then
 		warn "No hotfix branches exist."
                 warn ""
                 warn "You can start a new hotfix branch:"
@@ -83,38 +86,55 @@ cmd_list() {
 		local len=${#branch}
 		width=$(max $width $len)
 	done
+	for branch in $remote_hotfix_branches; do
+		local len=${#branch}
+		width=$(max $width $len)
+	done
 	width=$(($width+3))
 
-	local branch
-	for branch in $short_names; do
-		local fullname=$PREFIX$branch
-		local base=$(git merge-base "$fullname" "$MASTER_BRANCH")
-		local master_sha=$(git rev-parse "$MASTER_BRANCH")
-		local branch_sha=$(git rev-parse "$fullname")
-		if [ "$fullname" = "$current_branch" ]; then
-			printf "* "
-		else
-			printf "  "
-		fi
-		if flag verbose; then
-			printf "%-${width}s" "$branch"
-			if [ "$branch_sha" = "$master_sha" ]; then
-				printf "(no commits yet)"
-			else
-				local tagname=$(git name-rev --tags --no-undefined --name-only "$base")
-				local nicename
-				if [ "$tagname" != "" ]; then
-					nicename=$tagname
-				else
-					nicename=$(git rev-parse --short "$base")
-				fi
-				printf "(based on $nicename)"
-			fi
-		else
-			printf "%s" "$branch"
-		fi
+	if [ "$hotfix_branches" ]; then
+		printf "Local hotfix branches:"
 		echo
-	done
+		local branch
+		for branch in $short_names; do
+			local fullname=$PREFIX$branch
+			local base=$(git merge-base "$fullname" "$MASTER_BRANCH")
+			local master_sha=$(git rev-parse "$MASTER_BRANCH")
+			local branch_sha=$(git rev-parse "$fullname")
+			if [ "$fullname" = "$current_branch" ]; then
+				printf "* "
+			else
+				printf "  "
+			fi
+			if flag verbose; then
+				printf "%-${width}s" "$branch"
+				if [ "$branch_sha" = "$master_sha" ]; then
+					printf "(no commits yet)"
+				else
+					local tagname=$(git name-rev --tags --no-undefined --name-only "$base")
+					local nicename
+					if [ "$tagname" != "" ]; then
+						nicename=$tagname
+					else
+						nicename=$(git rev-parse --short "$base")
+					fi
+					printf "(based on $nicename)"
+				fi
+			else
+				printf "%s" "$branch"
+			fi
+			echo
+		done
+	fi
+	if [ "$remote_hotfix_branches" ]; then
+		printf "Remote hotfix branches:"
+		echo
+		for branch in $remote_hotfix_branches; do
+			printf "  "
+			printf "%s" "remotes/$branch"
+			echo
+		done
+	fi
 }
 
 cmd_help() {
@@ -129,7 +149,60 @@ parse_args() {
 
 	# read arguments into global variables
 	VERSION=$1
-	BRANCH=$PREFIX$VERSION
+	# check whether the user has already added the version tag prefix or not
+	if { echo "$VERSION" | grep -q "^$VERSION_PREFIX"; } then
+		local len=${#VERSION_PREFIX}
+		VERSION=${VERSION:$len}
+	fi
+
+	# check whether the user has provided a version tag with hotfix tag or not
+	local number_dots
+	# if there is only a dot at the end of the input string, kill it
+	if { echo "$VERSION" | grep -q "[.]$"; } then
+		local len=${#VERSION}-1
+		VERSION=${VERSION:0:len}
+	fi
+	# is there is no hotfix tag provided by the user, get the latest one from the server
+	number_dots="${VERSION//[^.]}"
+	if [ "${#number_dots}" = 1 ]; then
+		local last=0
+		local tag
+		for tag in $(git_do for-each-ref refs/tags/ --format='%(refname)'); do
+			if { echo "$tag" | grep -q "$VERSION"; } then
+				local len=8+${#VERSION}+${#VERSION}+1
+				local shorttag
+				shorttag=${tag:len}
+				local nextdot
+				nextdot=$(expr index "$shorttag" .)
+				if [[ "$nextdot" > 0 ]]; then
+					((nextdot-=1))
+					shorttag=${shorttag:0:nextdot}
+				fi
+				last=$shorttag
+			fi
+		done
+		local newlast
+		((newlast=last+1))
+		NEW_BRANCH=$PREFIX$VERSION_PREFIX$VERSION.$newlast
+		NEW_VERSION=$VERSION.$newlast
+		VERSION=$VERSION.$last
+	elif [ "${#number_dots}" = 2 ]; then
+		local nextdot
+		nextdot=$(expr index "$VERSION" .)
+		local prefix
+		prefix=${VERSION:0: nextdot+1}
+		local suffix
+		suffix=${VERSION:nextdot}
+		nextdot=$(expr index "$suffix" .)
+		local last
+		last=${suffix:nextdot}
+		((newlast=last+1))
+		NEW_BRANCH=$PREFIX$VERSION_PREFIX$prefix.$newlast
+		NEW_VERSION=$prefix.$newlast
+	elif [[ "${#number_dots}" > 2 ]]; then
+		die "Subhotfix branches are not supported."
+	fi
+	BRANCH=$PREFIX$VERSION_PREFIX$VERSION
 }
 
 require_version_arg() {
@@ -160,35 +233,43 @@ cmd_start() {
 	DEFINE_boolean fetch false "fetch from $ORIGIN before performing finish" F
 	parse_args "$@"
 	BASE=${2:-$MASTER_BRANCH}
+
 	require_version_arg
-	require_base_is_on_master
+#	require_base_is_on_master
 	require_no_existing_hotfix_branches
 
 	# sanity checks
 	require_clean_working_tree
-	require_branch_absent "$BRANCH"
-	require_tag_absent "$VERSION_PREFIX$VERSION"
+	require_branch_absent "$NEW_BRANCH"
+	require_tag_existing "$VERSION_PREFIX$VERSION"
+	require_tag_absent "$VERSION_PREFIX$NEW_VERSION"
 	if flag fetch; then
-		git_do fetch -q "$ORIGIN" "$MASTER_BRANCH"
+		git_do fetch -q "$ORIGIN" "$MASTER_BRANCH" >/dev/null 2>&1
 	fi
 	if has "$ORIGIN/$MASTER_BRANCH" $(git_remote_branches); then
 		require_branches_equal "$MASTER_BRANCH" "$ORIGIN/$MASTER_BRANCH"
 	fi
 
-	# create branch
-	git_do checkout -b "$BRANCH" "$BASE"
+	# create the local branch and the corresponding remote branch
+	if ! git_do checkout -b "$NEW_BRANCH" "$VERSION_PREFIX$VERSION" >/dev/null 2>&1; then
+		die "Could not create hotfix branch '$NEW_BRANCH'"
+	else
+		git_do push origin "$NEW_BRANCH" >/dev/null 2>&1
+	fi
 
 	echo
 	echo "Summary of actions:"
-	echo "- A new branch '$BRANCH' was created, based on '$BASE'"
-	echo "- You are now on branch '$BRANCH'"
+	echo "- A new local branch '$NEW_BRANCH' was created, based on '$VERSION_PREFIX$VERSION'"
+	echo "- A new remote branch '$NEW_BRANCH' was created, based on the local one"
+	echo "- You are now on branch '$NEW_BRANCH'"
 	echo
-	echo "Follow-up actions:"
-	echo "- Bump the version number now!"
-	echo "- Start committing your hot fixes"
-	echo "- When done, run:"
+#	echo "Follow-up actions:"
+#	echo "- Bump the version number now!"
+#	echo "- Start committing your hot fixes"
+#	echo "- When done, run:"
+	echo "Now, start committing your hotfixes. When done, use:"
 	echo
-	echo "     git-flow hotfix finish '$VERSION'"
+	echo "     git-flow hotfix finish '$VERSION_PREFIX$NEW_VERSION'"
 	echo
 }
 
@@ -215,6 +296,7 @@ cmd_publish() {
 	echo "Summary of actions:"
 	echo "- A new remote branch '$BRANCH' was created"
 	echo "- The local branch '$BRANCH' was configured to track the remote branch"
+	echo "- The old remote branch '$BRANCH' has to be deleted manually"
 	echo "- You are now on branch '$BRANCH'"
 	echo
 }
@@ -240,14 +322,15 @@ cmd_track() {
 }
 
 cmd_finish() {
-	DEFINE_boolean fetch false "fetch from $ORIGIN before performing finish" F
+	DEFINE_boolean fetch true "fetch from remote branches before performing finish" F
 	DEFINE_boolean sign false "sign the release tag cryptographically" s
 	DEFINE_string signingkey "" "use the given GPG-key for the digital signature (implies -s)" u
 	DEFINE_string message "" "use the given tag message" m
 	DEFINE_string messagefile "" "use the contents of the given file as tag message" f
-	DEFINE_boolean push false "push to $ORIGIN after performing finish" p
+	DEFINE_boolean push true "push to $ORIGIN after performing finish" p
 	DEFINE_boolean keep false "keep branch after performing finish" k
 	DEFINE_boolean notag false "don't tag this release" n
+	DEFINE_boolean release false "merge the current hotfix branch into the release branch instead of the develop branch" r
 	parse_args "$@"
 	require_version_arg
 
@@ -259,17 +342,20 @@ cmd_finish() {
 	# sanity checks
 	require_branch "$BRANCH"
 	require_clean_working_tree
-	if flag fetch; then
-		git_do fetch -q "$ORIGIN" "$MASTER_BRANCH" || \
-		  die "Could not fetch $MASTER_BRANCH from $ORIGIN."
-		git_do fetch -q "$ORIGIN" "$DEVELOP_BRANCH" || \
-		  die "Could not fetch $DEVELOP_BRANCH from $ORIGIN."
+	if has "$ORIGIN/$BRANCH" $(git_remote_branches); then
+		if flag fetch; then
+			git_do fetch -q "$ORIGIN" "$MASTER_BRANCH" || \
+			  die "Could not fetch $MASTER_BRANCH from $ORIGIN."
+			git_do fetch -q "$ORIGIN" "$BRANCH" || \
+			  die "Could not fetch $BRANCH from $ORIGIN."
+		fi
 	fi
+
 	if has "$ORIGIN/$MASTER_BRANCH" $(git_remote_branches); then
 		require_branches_equal "$MASTER_BRANCH" "$ORIGIN/$MASTER_BRANCH"
 	fi
-	if has "$ORIGIN/$DEVELOP_BRANCH" $(git_remote_branches); then
-		require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
+	if has "$ORIGIN/$BRANCH" $(git_remote_branches); then
+		require_branches_equal "$BRANCH" "$ORIGIN/$BRANCH"
 	fi
 
 	# try to merge into master
@@ -299,51 +385,139 @@ cmd_finish() {
 		fi
 	fi
 
-	# try to merge into develop
-	# in case a previous attempt to finish this release branch has failed,
-	# but the merge into develop was successful, we skip it now
-	if ! git_is_branch_merged_into "$BRANCH" "$DEVELOP_BRANCH"; then
-		git_do checkout "$DEVELOP_BRANCH" || \
-		  die "Could not check out $DEVELOP_BRANCH."
+	if flag release; then
+		local remote_tag="$ORIGIN/$(git config --get gitflow.prefix.release)"
+		if ! has_like $remote_tag $(git_remote_branches); then
+			warn "A release branch does not exist. Merging into develop branch instead."
+			release=false
+		else
+			local remote_branches
+			remote_branches="$(git_remote_branches)"
+			local remote_branch="not_found"
+			local find_branch
+			for find_branch in $remote_branches; do
+				if { echo "$find_branch" | grep -q "^$remote_tag"; } then
+				remote_branch="$find_branch"
+				fi
+			done
+			local local_branches
+			local_branches="$(git_local_branches)"
+			local local_branch="not_found"
+			local local_tag="$(git config --get gitflow.prefix.release)"
+			for find_branch in $local_branches; do
+				if { echo "$find_branch" | grep -q "^$local_tag"; } then
+				local_branch="$find_branch"
+				fi
+			done
+			if [ "$remote_branch" = "not_found" ]; then
+				warn "A release branch does not exist. Merging into develop branch instead."
+				release=false
+			else
+				if ! git_is_branch_merged_into "$BRANCH" "$remote_branch"; then
+					# try to merge into remote release branch
+					# in case a previous attempt to finish this hotfix branch has failed,
+					# but the merge into the remote release branch was successful, we skip it now
+#					local remote_shortname
+#					local len=${#remote_tag}
+#					remote_shortname=${remote_branch:len}
+					local len=${#ORIGIN}
+					((len+=1))
+					local local_name=${remote_branch:len}
+					if [ "$local_branch" = "not_found" ]; then
+						git_do branch --track $local_name $remote_branch >/dev/null 2>&1
+						git_do checkout "$local_name" >/dev/null 2>&1 || \
+						  die "Could not check out $local_name."
+						git_do merge --no-ff "$BRANCH" >/dev/null 2>&1 || \
+						  die "There were merge conflicts."
+						  # TODO: What do we do now?
+						git_do push "$ORIGIN" "$local_name" >/dev/null 2>&1 || \
+						  die "Could not push to $local_name from $ORIGIN."
+						git_do checkout "$BRANCH" >/dev/null 2>&1 || \
+						  die "Could not check out $BRANCH."
+						git_do branch -d "$local_name" >/dev/null 2>&1
+					else
+						git_do checkout "$local_name" >/dev/null 2>&1 || \
+						  die "Could not check out $local_name."
+#						if flag fetch; then
+							git_do fetch "$ORIGIN" "$local_name" >/dev/null 2>&1 || \
+							  die "Could not fetch $local_name from $ORIGIN."
+#						fi
+						git_do merge --no-ff "$BRANCH" >/dev/null 2>&1 || \
+						  die "There were merge conflicts."
+						  # TODO: What do we do now?
+						git_do push "$ORIGIN" "$local_name" >/dev/null 2>&1 || \
+						  die "Could not push to $local_name from $ORIGIN."
+						git_do checkout "$BRANCH" >/dev/null 2>&1 || \
+						  die "Could not check out $BRANCH."
+						
+					fi
+				fi
+			fi
+		fi
+	fi
 
-		# TODO: Actually, accounting for 'git describe' pays, so we should
-		# ideally git merge --no-ff $tagname here, instead!
-		git_do merge --no-ff "$BRANCH" || \
-		  die "There were merge conflicts."
-		  # TODO: What do we do now?
+	if ! flag release; then
+		# try to merge into develop
+		# in case a previous attempt to finish this hotfix branch has failed,
+		# but the merge into develop was successful, we skip it now
+		git_do fetch -q "$ORIGIN" "$DEVELOP_BRANCH" >/dev/null 2>&1 || \
+		  die "Could not fetch $DEVELOP_BRANCH from $ORIGIN."
+		if ! git_is_branch_merged_into "$BRANCH" "$ORIGIN/$DEVELOP_BRANCH"; then
+			git_do checkout "$DEVELOP_BRANCH" >/dev/null 2>&1 || \
+			  die "Could not check out $DEVELOP_BRANCH."
+
+			# TODO: Actually, accounting for 'git describe' pays, so we should
+			# ideally git merge --no-ff $tagname here, instead!
+			git_do merge --no-ff "$BRANCH" >/dev/null 2>&1 || \
+			  die "There were merge conflicts."
+			  # TODO: What do we do now?
+
+			git_do push "$ORIGIN" "$DEVELOP_BRANCH" >/dev/null 2>&1 || \
+			  die "Could not push to $DEVELOP_BRANCH from $ORIGIN."
+			git_do checkout "$BRANCH" >/dev/null 2>&1 || \
+			  die "Could not check out $BRANCH."
+		fi
+	fi
+
+	if flag push; then
+		git_do push "$ORIGIN" "$MASTER_BRANCH" >/dev/null 2>&1 || \
+			die "Could not push to $MASTER_BRANCH from $ORIGIN."
+		if noflag notag; then
+			git_do push --tags "$ORIGIN" >/dev/null 2>&1 || \
+				die "Could not push tags to $ORIGIN."
+		fi
 	fi
 
 	# delete branch
 	if noflag keep; then
-		git_do branch -d "$BRANCH"
-	fi
-
-	if flag push; then
-		git_do push "$ORIGIN" "$DEVELOP_BRANCH" || \
-			die "Could not push to $DEVELOP_BRANCH from $ORIGIN."
-		git_do push "$ORIGIN" "$MASTER_BRANCH" || \
-			die "Could not push to $MASTER_BRANCH from $ORIGIN."
-		if noflag notag; then
-			git_do push --tags "$ORIGIN" || \
-				die "Could not push tags to $ORIGIN."
-		fi
+		git_do checkout "$DEVELOP_BRANCH" >/dev/null 2>&1 || \
+		  die "Could not check out $BRANCH."
+		git_do branch -d "$BRANCH" >/dev/null 2>&1
+		git_do push "$ORIGIN" ":refs/heads/$BRANCH" >/dev/null 2>&1
 	fi
 
 	echo
 	echo "Summary of actions:"
 	echo "- Latest objects have been fetched from '$ORIGIN'"
 	echo "- Hotfix branch has been merged into '$MASTER_BRANCH'"
-	if noflag notag; then
+#	if noflag notag; then
 		echo "- The hotfix was tagged '$VERSION_PREFIX$VERSION'"
-	fi
-	echo "- Hotfix branch has been back-merged into '$DEVELOP_BRANCH'"
-	if flag keep; then
-		echo "- Hotfix branch '$BRANCH' is still available"
+#	fi
+	if flag release; then
+		echo "- Hotfix branch has been back-merged into the existing release branch"
 	else
-		echo "- Hotfix branch '$BRANCH' has been deleted"
+		echo "- Hotfix branch has been back-merged into '$DEVELOP_BRANCH'"
+	fi
+	if flag keep; then
+		echo "- Hotfix branch '$BRANCH' (local and remote) is still available"
+	else
+		echo "- Hotfix branch '$BRANCH' (local and remote) has been deleted"
 	fi
 	if flag push; then
 		echo "- '$DEVELOP_BRANCH', '$MASTER_BRANCH' and tags have been pushed to '$ORIGIN'"
+	fi
+	if noflag keep; then
+		echo "- You are now on branch '$DEVELOP_BRANCH'"
 	fi
 	echo
 }
